import Mathlib.Tactic

/-!
# Yang-Mills RG Bootstrap Audit

Goertzel's Yang-Mills attempt advertises an extended-extraction RG contraction:
for block factor `b = 2` and extraction dimension `dmax = 16`, the irrelevant
factor is `b^(3-dmax) = 2^-13`, and the claimed combinatorial constant is
bounded by `2224`, giving a product below `1`.

This file isolates that numerical and recurrence-level obligation.  It does not
prove the polymer RG estimates; it supplies a small audit surface that future
formalizations can instantiate once those estimates are available.
-/

set_option autoImplicit false

noncomputable section

namespace Mettapedia
namespace QuantumTheory
namespace YangMills

/-- Irrelevant scaling factor `b^(3-dmax)` used by the extended-extraction
discussion.  The exponent is an integer because the useful cases have
`dmax > 3`. -/
def irrelevantScale (b dmax : ℕ) : ℝ :=
  (b : ℝ) ^ (3 - (dmax : ℤ))

/-- A one-step RG gain is a genuine contraction when it is nonnegative and
strictly below `1`. -/
def IsRGContractionGain (κ : ℝ) : Prop :=
  0 ≤ κ ∧ κ < 1

/-- The route-level contraction audit for a combinatorial constant and an
irrelevant scaling factor. -/
def HasRGContraction (C scale : ℝ) : Prop :=
  0 ≤ C ∧ 0 ≤ scale ∧ C * scale < 1

/-- The extended-extraction audit specialized to `λ = b^(3-dmax)`. -/
def HasExtendedExtractionContraction (C : ℝ) (b dmax : ℕ) : Prop :=
  HasRGContraction C (irrelevantScale b dmax)

/-- Affine one-step RG bootstrap bound.  A future polymer estimate can
instantiate `a` with a norm of irrelevant polymer activity. -/
def AffineRGStepBound (κ ε : ℝ) (a : ℕ → ℝ) : Prop :=
  ∀ n : ℕ, a (n + 1) ≤ κ * a n + ε

/-- The finite-iterate envelope generated by the affine recurrence
`x_{n+1} = κ x_n + ε`. -/
def affineRGEnvelope (κ ε a0 : ℝ) : ℕ → ℝ
  | 0 => a0
  | n + 1 => κ * affineRGEnvelope κ ε a0 n + ε

/-- If an affine RG step maps the closed interval `(-∞, B]` into itself, then a
sequence starting below `B` remains below `B` at every finite scale. -/
theorem AffineRGStepBound.bound_by_invariant_interval
    {κ ε B : ℝ} {a : ℕ → ℝ}
    (hstep : AffineRGStepBound κ ε a)
    (hκ_nonneg : 0 ≤ κ)
    (hε : ε ≤ (1 - κ) * B)
    (h0 : a 0 ≤ B) :
    ∀ n : ℕ, a n ≤ B := by
  intro n
  induction n with
  | zero => exact h0
  | succ n ih =>
      have hstepn : a (n + 1) ≤ κ * a n + ε := hstep n
      have hmul : κ * a n ≤ κ * B :=
        mul_le_mul_of_nonneg_left ih hκ_nonneg
      nlinarith

/-- An affine one-step bound is dominated by the exact affine envelope at every
finite iterate. -/
theorem AffineRGStepBound.le_affineRGEnvelope
    {κ ε : ℝ} {a : ℕ → ℝ}
    (hstep : AffineRGStepBound κ ε a)
    (hκ_nonneg : 0 ≤ κ) :
    ∀ n : ℕ, a n ≤ affineRGEnvelope κ ε (a 0) n := by
  intro n
  induction n with
  | zero =>
      simp [affineRGEnvelope]
  | succ n ih =>
      have hstepn : a (n + 1) ≤ κ * a n + ε := hstep n
      have hmul : κ * a n ≤ κ * affineRGEnvelope κ ε (a 0) n :=
        mul_le_mul_of_nonneg_left ih hκ_nonneg
      calc
        a (n + 1) ≤ κ * a n + ε := hstepn
        _ ≤ κ * affineRGEnvelope κ ε (a 0) n + ε := by
          nlinarith [hmul]
        _ = affineRGEnvelope κ ε (a 0) (n + 1) := by
          simp [affineRGEnvelope]

/-- With zero additive error, the affine envelope is the usual geometric
envelope. -/
theorem affineRGEnvelope_zero_error
    (κ a0 : ℝ) :
    ∀ n : ℕ, affineRGEnvelope κ 0 a0 n = κ ^ n * a0 := by
  intro n
  induction n with
  | zero =>
      simp [affineRGEnvelope]
  | succ n ih =>
      simp [affineRGEnvelope, ih, pow_succ]
      ring

/-- Homogeneous RG recurrences are bounded by a geometric decay/growth
envelope. -/
theorem AffineRGStepBound.bound_by_geometric_of_zero_error
    {κ : ℝ} {a : ℕ → ℝ}
    (hstep : AffineRGStepBound κ 0 a)
    (hκ_nonneg : 0 ≤ κ) :
    ∀ n : ℕ, a n ≤ κ ^ n * a 0 := by
  intro n
  rw [← affineRGEnvelope_zero_error κ (a 0) n]
  exact hstep.le_affineRGEnvelope hκ_nonneg n

/-- Exact value of the irrelevant scale advertised for extended extraction with
`b = 2` and `dmax = 16`. -/
theorem irrelevantScale_two_sixteen :
    irrelevantScale 2 16 = (1 : ℝ) / 8192 := by
  norm_num [irrelevantScale]

/-- Exact value of the naive marginal-only scale with `b = 2` and `dmax = 4`. -/
theorem irrelevantScale_two_four :
    irrelevantScale 2 4 = (1 : ℝ) / 2 := by
  norm_num [irrelevantScale]

/-- Exact value at the manuscript's nearest even extraction depth below `16`. -/
theorem irrelevantScale_two_fourteen :
    irrelevantScale 2 14 = (1 : ℝ) / 2048 := by
  norm_num [irrelevantScale]

/-- Exact value at the odd extraction depth immediately below `16`.  This is
recorded to keep the crux audit honest: the same-constant blocker below is an
even-depth/manuscript-shape obstruction, not an obstruction to the raw natural
number `dmax = 15` arithmetic. -/
theorem irrelevantScale_two_fifteen :
    irrelevantScale 2 15 = (1 : ℝ) / 4096 := by
  norm_num [irrelevantScale]

/-- For any natural block factor and extraction depth at least the
marginal dimension `3`, the integer-exponent irrelevant scale is exactly the
reciprocal of the positive natural power `b^(dmax - 3)`. -/
theorem irrelevantScale_eq_inv_pow_of_three_le
    {b dmax : ℕ} (hdmax : 3 ≤ dmax) :
    irrelevantScale b dmax = ((b : ℝ) ^ (dmax - 3))⁻¹ := by
  unfold irrelevantScale
  have hsub : (3 : ℤ) - (dmax : ℤ) = -(((dmax - 3 : ℕ) : ℤ)) := by
    omega
  rw [hsub, zpow_neg, zpow_natCast]

/-- Exact threshold form of the positive-block-factor contraction audit: once
`b > 0` and `dmax ≥ 3`, contraction with constant `C` is equivalent to `C`
being nonnegative and strictly below `b^(dmax-3)`. -/
theorem rgContraction_iff_constant_lt_pow_of_pos_of_three_le
    {C : ℝ} {b dmax : ℕ} (hb : 0 < b) (hdmax : 3 ≤ dmax) :
    HasExtendedExtractionContraction C b dmax ↔
      0 ≤ C ∧ C < (b : ℝ) ^ (dmax - 3) := by
  have hscale_pos : 0 < (b : ℝ) ^ (dmax - 3) :=
    pow_pos (Nat.cast_pos.mpr hb) _
  rw [HasExtendedExtractionContraction, HasRGContraction]
  constructor
  · intro h
    refine ⟨h.1, ?_⟩
    have hprod : C * ((b : ℝ) ^ (dmax - 3))⁻¹ < 1 := by
      simpa [irrelevantScale_eq_inv_pow_of_three_le hdmax] using h.2.2
    rw [mul_inv_lt_iff₀ hscale_pos] at hprod
    simpa using hprod
  · intro h
    refine ⟨h.1, ?_, ?_⟩
    · rw [irrelevantScale_eq_inv_pow_of_three_le hdmax]
      exact inv_nonneg.mpr (le_of_lt hscale_pos)
    · have hprod : C * ((b : ℝ) ^ (dmax - 3))⁻¹ < 1 := by
        rw [mul_inv_lt_iff₀ hscale_pos]
        simpa using h.2
      simpa [irrelevantScale_eq_inv_pow_of_three_le hdmax] using hprod

/-- Any positive-block-factor contraction certificate at depth `dmax ≥ 3`
forces the recombination constant below the exact power threshold. -/
theorem rgContraction_forces_constant_lt_pow_of_pos_of_three_le
    {C : ℝ} {b dmax : ℕ} (hb : 0 < b) (hdmax : 3 ≤ dmax)
    (h : HasExtendedExtractionContraction C b dmax) :
    C < (b : ℝ) ^ (dmax - 3) :=
  ((rgContraction_iff_constant_lt_pow_of_pos_of_three_le
    (C := C) hb hdmax).mp h).2

/-- General same-constant blocker: for any positive block factor, if the
explicit power threshold has not exceeded the advertised recombination bound
`2224`, then that advertised bound cannot certify the RG contraction. -/
theorem not_rgContraction_2224_of_pow_le_of_pos_of_three_le
    {b dmax : ℕ} (hb : 0 < b) (hdmax : 3 ≤ dmax)
    (hpow : (b : ℝ) ^ (dmax - 3) ≤ 2224) :
    ¬ HasExtendedExtractionContraction 2224 b dmax := by
  intro h
  have hthreshold :
      (2224 : ℝ) < (b : ℝ) ^ (dmax - 3) :=
    rgContraction_forces_constant_lt_pow_of_pos_of_three_le hb hdmax h
  exact (not_lt_of_ge hpow) hthreshold

/-- For block factor `2` and extraction depth at least the marginal dimension
`3`, the integer-exponent irrelevant scale is exactly the reciprocal of the
positive natural power `2^(dmax - 3)`. -/
theorem irrelevantScale_two_eq_inv_pow_of_three_le
    {dmax : ℕ} (hdmax : 3 ≤ dmax) :
    irrelevantScale 2 dmax = ((2 : ℝ) ^ (dmax - 3))⁻¹ := by
  simpa using
    irrelevantScale_eq_inv_pow_of_three_le
      (b := 2) hdmax

/-- Exact threshold form of the block-factor-`2` contraction audit: once
`dmax ≥ 3`, contraction with constant `C` is equivalent to `C` being
nonnegative and strictly below `2^(dmax-3)`. -/
theorem rgContraction_two_iff_constant_lt_pow_of_three_le
    {C : ℝ} {dmax : ℕ} (hdmax : 3 ≤ dmax) :
    HasExtendedExtractionContraction C 2 dmax ↔
      0 ≤ C ∧ C < (2 : ℝ) ^ (dmax - 3) := by
  exact rgContraction_iff_constant_lt_pow_of_pos_of_three_le
    (b := 2) (by norm_num) hdmax

/-- Any block-factor-`2` contraction certificate at depth `dmax ≥ 3` forces
the recombination constant below the exact power threshold. -/
theorem rgContraction_two_forces_constant_lt_pow_of_three_le
    {C : ℝ} {dmax : ℕ} (hdmax : 3 ≤ dmax)
    (h : HasExtendedExtractionContraction C 2 dmax) :
    C < (2 : ℝ) ^ (dmax - 3) :=
  rgContraction_forces_constant_lt_pow_of_pos_of_three_le
    (b := 2) (by norm_num) hdmax h

/-- The advertised numerical slack: `2224 * 2^-13 < 1`. -/
theorem rgContraction_2224_two_sixteen :
    HasExtendedExtractionContraction 2224 2 16 := by
  refine ⟨by norm_num, by rw [irrelevantScale_two_sixteen]; norm_num, ?_⟩
  rw [irrelevantScale_two_sixteen]
  norm_num

/-- Exact advertised one-step gain for the extended-extraction constants. -/
theorem rgGain_2224_two_sixteen_eq :
    (2224 : ℝ) * irrelevantScale 2 16 = (139 : ℝ) / 512 := by
  rw [irrelevantScale_two_sixteen]
  norm_num

/-- The advertised contraction has better than one-third slack. -/
theorem rgGain_2224_two_sixteen_lt_one_third :
    (2224 : ℝ) * irrelevantScale 2 16 < (1 : ℝ) / 3 := by
  rw [rgGain_2224_two_sixteen_eq]
  norm_num

/-- The same advertised constant is not a contraction at the naive
`dmax = 4` scale.  This is a concrete same-constant blocker for any attempted
repair that keeps the manuscript's combinatorial bound but removes the extended
extraction depth. -/
theorem not_rgContraction_2224_two_four :
    ¬ HasExtendedExtractionContraction 2224 2 4 := by
  intro h
  have hprod : (2224 : ℝ) * irrelevantScale 2 4 < 1 := h.2.2
  rw [irrelevantScale_two_four] at hprod
  norm_num at hprod

/-- Exact same-constant gain at the naive marginal-only extraction scale. -/
theorem rgGain_2224_two_four_eq :
    (2224 : ℝ) * irrelevantScale 2 4 = 1112 := by
  rw [irrelevantScale_two_four]
  norm_num

/-- Exact same-constant gain at the nearest even extraction depth below `16`. -/
theorem rgGain_2224_two_fourteen_eq :
    (2224 : ℝ) * irrelevantScale 2 14 = (139 : ℝ) / 128 := by
  rw [irrelevantScale_two_fourteen]
  norm_num

/-- Exact same-constant gain at raw natural extraction depth `15`. -/
theorem rgGain_2224_two_fifteen_eq :
    (2224 : ℝ) * irrelevantScale 2 15 = (139 : ℝ) / 256 := by
  rw [irrelevantScale_two_fifteen]
  norm_num

/-- In the raw natural-number model, `dmax = 15` already contracts with the
advertised constant.  The route-level blocker should therefore be read as an
even canonical-dimension obstruction, matching the manuscript's dimensions
`4, 6, ..., dmax`. -/
theorem rgContraction_2224_two_fifteen :
    HasExtendedExtractionContraction 2224 2 15 := by
  refine ⟨by norm_num, by rw [irrelevantScale_two_fifteen]; norm_num, ?_⟩
  rw [irrelevantScale_two_fifteen]
  norm_num

/-- Any contraction proof at `dmax = 14` must improve the linear recombination
constant below `2048`.  The manuscript's advertised bound `2224` is therefore
insufficient for this lower extraction depth. -/
theorem rgContraction_two_fourteen_forces_constant_lt_2048
    {C : ℝ} (h : HasExtendedExtractionContraction C 2 14) :
    C < 2048 := by
  have hprod : C * irrelevantScale 2 14 < 1 := h.2.2
  rw [irrelevantScale_two_fourteen] at hprod
  nlinarith

/-- Same-constant blocker at the nearest even extraction depth below `16`. -/
theorem not_rgContraction_2224_two_fourteen :
    ¬ HasExtendedExtractionContraction 2224 2 14 := by
  intro h
  have hC : (2224 : ℝ) < 2048 :=
    rgContraction_two_fourteen_forces_constant_lt_2048 h
  norm_num at hC

/-- Any proposed contraction certificate at `dmax = 14` fails once the linear
recombination constant is at least `2048`. -/
theorem not_rgContraction_two_fourteen_of_ge_2048
    {C : ℝ} (hC : 2048 ≤ C) :
    ¬ HasExtendedExtractionContraction C 2 14 := by
  intro h
  have hlt : C < 2048 :=
    rgContraction_two_fourteen_forces_constant_lt_2048 h
  exact (not_lt_of_ge hC) hlt

/-- Lower-depth threshold blocker: with block factor `2`, no extraction depth
`dmax ≤ 14` can contract once the recombination constant is at least `2048`. -/
theorem not_rgContraction_two_of_ge_2048_of_dmax_le_fourteen
    {C : ℝ} {dmax : ℕ} (hC : 2048 ≤ C) (hdmax : dmax ≤ 14) :
    ¬ HasExtendedExtractionContraction C 2 dmax := by
  intro h
  have hprod : C * irrelevantScale 2 dmax < 1 := h.2.2
  interval_cases dmax <;> norm_num [irrelevantScale] at hprod <;> nlinarith

/-- Same-constant lower-depth blocker: with the advertised constant `2224` and
block factor `2`, no extraction depth `dmax ≤ 14` yields the needed linear
contraction. -/
theorem not_rgContraction_2224_two_of_dmax_le_fourteen
    {dmax : ℕ} (hdmax : dmax ≤ 14) :
    ¬ HasExtendedExtractionContraction 2224 2 dmax := by
  intro h
  have hprod : (2224 : ℝ) * irrelevantScale 2 dmax < 1 := h.2.2
  interval_cases dmax <;> norm_num [irrelevantScale] at hprod

/-- Any larger combinatorial constant still contracts at the extended scale
provided it is bounded by `2224`. -/
theorem rgContraction_of_nonneg_le_2224_two_sixteen
    {C : ℝ} (hCnonneg : 0 ≤ C) (hC : C ≤ 2224) :
    HasExtendedExtractionContraction C 2 16 := by
  refine ⟨hCnonneg, by rw [irrelevantScale_two_sixteen]; norm_num, ?_⟩
  have hscale_nonneg : 0 ≤ irrelevantScale 2 16 := by
    rw [irrelevantScale_two_sixteen]
    norm_num
  have hmul : C * irrelevantScale 2 16 ≤ 2224 * irrelevantScale 2 16 :=
    mul_le_mul_of_nonneg_right hC hscale_nonneg
  have hstrict : (2224 : ℝ) * irrelevantScale 2 16 < 1 := by
    rw [irrelevantScale_two_sixteen]
    norm_num
  exact lt_of_le_of_lt hmul hstrict

/-- A nonnegative contraction audit exposes the one-step gain as a contraction
gain. -/
theorem HasRGContraction.gain
    {C scale : ℝ} (h : HasRGContraction C scale) :
    IsRGContractionGain (C * scale) :=
  ⟨mul_nonneg h.1 h.2.1, h.2.2⟩

end YangMills
end QuantumTheory
end Mettapedia
