import Mettapedia.Computability.PNP.PNPv13AppendixDLocalLockedCore

/-!
# PNP v13: public syntax discipline for Appendix D locked cores

Appendix D.29--D.31 require public template and surface atoms to normalize to
neutral evidence, excluding public message/target tags from the visible syntax.
This file adds that discipline to the local locked-core interface and checks
whether it can replace Appendix D.8.

It cannot: the one-bit local countermodel can be equipped with a completely
neutral public syntax record.  Thus bounded-local `Lock`/`Read`, D.7,
deterministic readout, and public syntax normalization still do not imply
locked-message rigidity.
-/

namespace Mettapedia.Computability.PNP

universe u v w x y z q

/-- The public primitive atoms generated by the D.29 public syntax record:
template atoms and surface atoms.  Their semantics must normalize through the
neutral alphabet. -/
inductive AppendixDPublicPrimitive (Template : Type u) (Surface : Type v) where
  | template : Template → AppendixDPublicPrimitive Template Surface
  | surface : Surface → AppendixDPublicPrimitive Template Surface

/-- Appendix D.29 public syntax record: template and surface alphabets only
rewrite through a neutral alphabet. -/
structure AppendixDPublicSyntaxRecord
    (Neutral : Type u) (Template : Type v) (Surface : Type w) where
  neutralFinite : Fintype Neutral
  templateFinite : Fintype Template
  surfaceFinite : Fintype Surface
  tpl : Template → Neutral
  surf : Surface → Neutral

namespace AppendixDPublicSyntaxRecord

variable {Neutral : Type u} {Template : Type v} {Surface : Type w}

/-- D.29 normalization of a public primitive atom to a neutral atom. -/
def normalize (S : AppendixDPublicSyntaxRecord Neutral Template Surface) :
    AppendixDPublicPrimitive Template Surface → Neutral
  | AppendixDPublicPrimitive.template θ => S.tpl θ
  | AppendixDPublicPrimitive.surface σ => S.surf σ

/-- D.31, formal core: every primitive atom produced by public syntax
normalizes to neutral evidence. -/
theorem exists_neutral_normal_form
    (S : AppendixDPublicSyntaxRecord Neutral Template Surface)
    (a : AppendixDPublicPrimitive Template Surface) :
    ∃ n : Neutral, S.normalize a = n := by
  exact ⟨S.normalize a, rfl⟩

end AppendixDPublicSyntaxRecord

/-- A local locked core paired with D.29 public syntax data.  The public syntax
fields deliberately carry only atoms whose normalization passes through the
neutral alphabet. -/
structure AppendixDPublicSyntaxDisciplinedLocalCore
    (PublicLock : Type u) (QuotientCoord : Type v)
    (LockAuxCoord : Type w) (MessageCoord : Type x)
    (Neutral : Type y) (Template : Type z) (Surface : Type q) where
  core :
    AppendixDLocalBoolLockedCore
      PublicLock QuotientCoord LockAuxCoord MessageCoord
  publicSyntax : AppendixDPublicSyntaxRecord Neutral Template Surface
  templateAtoms : PublicLock → List Template
  surfaceAtoms : PublicLock → List Surface

namespace AppendixDPublicSyntaxDisciplinedLocalCore

variable {PublicLock : Type u} {QuotientCoord : Type v}
variable {LockAuxCoord : Type w} {MessageCoord : Type x}
variable {Neutral : Type y} {Template : Type z} {Surface : Type q}

/-- Forget the public syntax bookkeeping and keep the local locked core. -/
def toLocalCore
    (D : AppendixDPublicSyntaxDisciplinedLocalCore
      PublicLock QuotientCoord LockAuxCoord MessageCoord Neutral Template Surface) :
    AppendixDLocalBoolLockedCore
      PublicLock QuotientCoord LockAuxCoord MessageCoord :=
  D.core

/-- The semantic Appendix D locked core underlying a public-syntax-disciplined
local presentation. -/
def toAppendixDLockedCore
    (D : AppendixDPublicSyntaxDisciplinedLocalCore
      PublicLock QuotientCoord LockAuxCoord MessageCoord Neutral Template Surface) :
    AppendixDLockedCore
      PublicLock (QuotientCoord → Bool) (LockAuxCoord → Bool)
      (MessageCoord → Bool) :=
  D.core.toAppendixDLockedCore

/-- Every template atom listed in a public lock syntax has a neutral normal
form. -/
theorem templateAtom_neutral_normal_form
    (D : AppendixDPublicSyntaxDisciplinedLocalCore
      PublicLock QuotientCoord LockAuxCoord MessageCoord Neutral Template Surface)
    {Y : PublicLock} {θ : Template} (_hθ : θ ∈ D.templateAtoms Y) :
    ∃ n : Neutral,
      D.publicSyntax.normalize (AppendixDPublicPrimitive.template θ) = n := by
  exact D.publicSyntax.exists_neutral_normal_form
    (AppendixDPublicPrimitive.template θ)

/-- Every surface atom listed in a public lock syntax has a neutral normal
form. -/
theorem surfaceAtom_neutral_normal_form
    (D : AppendixDPublicSyntaxDisciplinedLocalCore
      PublicLock QuotientCoord LockAuxCoord MessageCoord Neutral Template Surface)
    {Y : PublicLock} {σ : Surface} (_hσ : σ ∈ D.surfaceAtoms Y) :
    ∃ n : Neutral,
      D.publicSyntax.normalize (AppendixDPublicPrimitive.surface σ) = n := by
  exact D.publicSyntax.exists_neutral_normal_form
    (AppendixDPublicPrimitive.surface σ)

end AppendixDPublicSyntaxDisciplinedLocalCore

/-- A singleton public syntax record: both visible public atom classes normalize
to the unique neutral atom. -/
def unitAppendixDPublicSyntaxRecord :
    AppendixDPublicSyntaxRecord Unit Unit Unit where
  neutralFinite := inferInstance
  templateFinite := inferInstance
  surfaceFinite := inferInstance
  tpl := fun _ => ()
  surf := fun _ => ()

/-- The local D.5 countermodel equipped with D.29--D.31 neutral public syntax. -/
def ambiguousPublicSyntaxDisciplinedLocalCore :
    AppendixDPublicSyntaxDisciplinedLocalCore
      Unit Unit Unit Unit Unit Unit Unit where
  core := ambiguousAppendixDLocalBoolLockedCore
  publicSyntax := unitAppendixDPublicSyntaxRecord
  templateAtoms := fun _ => [()]
  surfaceAtoms := fun _ => [()]

/-- The public syntax discipline really normalizes the listed template atom to
neutral evidence in the countermodel. -/
theorem ambiguousPublicSyntaxDisciplined_template_neutral :
    ∃ n : Unit,
      ambiguousPublicSyntaxDisciplinedLocalCore.publicSyntax.normalize
        (AppendixDPublicPrimitive.template ()) = n := by
  exact
    ambiguousPublicSyntaxDisciplinedLocalCore.templateAtom_neutral_normal_form
      (Y := ()) (θ := ()) (by simp [ambiguousPublicSyntaxDisciplinedLocalCore])

/-- The public syntax discipline really normalizes the listed surface atom to
neutral evidence in the countermodel. -/
theorem ambiguousPublicSyntaxDisciplined_surface_neutral :
    ∃ n : Unit,
      ambiguousPublicSyntaxDisciplinedLocalCore.publicSyntax.normalize
        (AppendixDPublicPrimitive.surface ()) = n := by
  exact
    ambiguousPublicSyntaxDisciplinedLocalCore.surfaceAtom_neutral_normal_form
      (Y := ()) (σ := ()) (by simp [ambiguousPublicSyntaxDisciplinedLocalCore])

/-- D.7 still holds after adding the neutral public syntax discipline. -/
theorem ambiguousPublicSyntaxDisciplined_lockSatisfiable :
    ambiguousPublicSyntaxDisciplinedLocalCore.toAppendixDLockedCore.LockSatisfiable :=
  ambiguousAppendixDLocalBoolLockedCore_lockSatisfiable

/-- Fixed-state readout determinism still holds after adding the neutral public
syntax discipline. -/
theorem ambiguousPublicSyntaxDisciplined_readDeterministic :
    ambiguousPublicSyntaxDisciplinedLocalCore.toAppendixDLockedCore.ReadDeterministic :=
  ambiguousAppendixDLocalBoolLockedCore_readDeterministic

/-- D.29--D.31 public syntax discipline, D.5 bounded locality, D.7, and
deterministic readout still do not imply D.8. -/
theorem ambiguousPublicSyntaxDisciplined_not_lockedMessageRigidity :
    ¬ AppendixDLockedCore.LockedMessageRigidity
        ambiguousPublicSyntaxDisciplinedLocalCore.toAppendixDLockedCore :=
  ambiguousAppendixDLocalBoolLockedCore_not_lockedMessageRigidity

end Mettapedia.Computability.PNP
