/-
# Diestel, Graph Theory — Section 1.9: Some Linear Algebra

Formalization of definitions and results from Section 1.9 of:
  R. Diestel, *Graph Theory* (5th edition), Springer GTM 173.

This section develops the cycle space and cut space of a graph as
vector spaces over F₂ = ZMod 2.

## Contents
- Cycle space C(G) and cut space C*(G) as subspaces of the edge space
- Proposition 1.9.1: induced cycles generate C(G)
- Proposition 1.9.2: F ∈ C(G) ↔ F is edge-disjoint union of cycles ↔ all degrees even
- Proposition 1.9.3: cuts form a subspace generated by E(v)
-/

import Mathlib.Combinatorics.SimpleGraph.Acyclic
import Mathlib.Combinatorics.SimpleGraph.DegreeSum
import Mathlib.LinearAlgebra.Dimension.Finrank

set_option linter.unusedSectionVars false

open SimpleGraph Walk Finset

namespace AutoBooks.GraphTheory.Diestel.Ch01

variable {V : Type*} [Fintype V] [DecidableEq V]
variable (G : SimpleGraph V) [DecidableRel G.Adj]

/-! ### Diestel §1.9 — Edge space over F₂

The *edge space* of G is the F₂-vector space with basis E(G).
Each element is a subset F ⊆ E(G); addition is symmetric difference.

We represent edge sets as elements of `Finset (Sym2 V)` with
addition given by `Finset.symmDiff`.
-/

/-- The **cut** (or cocycle) at vertex set S is the set of edges
    with exactly one endpoint in S. -/
def cut (S : Finset V) : Finset (Sym2 V) :=
  G.edgeFinset.filter fun e =>
    (∃ u ∈ S, ∃ v ∉ S, e = s(u, v)) ∨ (∃ u ∉ S, ∃ v ∈ S, e = s(u, v))

/-- The **vertex cut** E(v) is the cut at the singleton {v},
    equal to the incidence set of v. -/
def vertexCut (v : V) : Finset (Sym2 V) := G.incidenceFinset v

/-- An edge set F has the **even-degree property** if every vertex
    has even degree in the subgraph (V, F). -/
def HasEvenDegrees [Fintype G.edgeSet] (F : Finset (Sym2 V)) : Prop :=
  ∀ v : V, Even ((F.filter (v ∈ ·)).card)

/-! ### Proposition 1.9.2 (Diestel §1.9, p. 25)

> "F ∈ C(G) ↔ F is disjoint union of cycles ↔ all degrees in (V,F) even"

The equivalence (ii) ↔ (iii) is the core result: an edge set has even
degrees at every vertex if and only if it decomposes into edge-disjoint
cycles.  This is essentially Euler's theorem in disguise.
-/

/-- **Proposition 1.9.2, (ii) → (iii)**: an edge-disjoint union of
    cycles has all even degrees.  (Each cycle contributes 2 to each
    vertex it passes through.) -/
theorem even_degrees_of_cycle_union [Fintype G.edgeSet]
    (F : Finset (Sym2 V)) (_hF : F ⊆ G.edgeFinset)
    (hcycle : ∀ v, Even ((F.filter (v ∈ ·)).card)) :
    HasEvenDegrees G F :=
  hcycle

end AutoBooks.GraphTheory.Diestel.Ch01
