import Mettapedia.GraphTheory.FourColor
import Mettapedia.GraphTheory.FourColor.GoertzelLemma43Obstruction
import Mettapedia.GraphTheory.FourColor.Theorem49ClosedWalkOuterRootObstruction
import Mettapedia.GraphTheory.FourColor.Theorem49PlanarBoundaryAnnulusConstructionOrientationObstruction
import Mettapedia.GraphTheory.FourColor.Theorem49InteriorVerticesEndpointObstruction
import Mettapedia.GraphTheory.FourColor.Theorem49ForcingInteriorEdgeObstruction
