import Mettapedia.GraphTheory.FourColor.Theorem49BoundaryProjection

namespace Mettapedia.GraphTheory.FourColor

variable {V : Type*} [DecidableEq V]

/-- Definition 4.8 generator family built from an arbitrary set of admissible colorings rather
than the whole edge-Kempe closure of a chosen base coloring.  This is the right abstraction for
the finite lab certificates, which often use a much smaller explicit neighborhood. -/
def coloringGeneratorFamily {G : SimpleGraph V} {F : Type*}
    (faceBoundary : F → Finset G.edgeSet) (colorings : Set (G.EdgeColoring Color)) :
    Set (G.edgeSet → Color) :=
  {x | ∃ C ∈ colorings, ∃ f : F, ∃ a b : Color,
      ValidColorPair a b ∧ x = polarizedFaceGenerator C a b (faceBoundary f)}

theorem mem_coloringGeneratorFamily_iff {G : SimpleGraph V} {F : Type*}
    (faceBoundary : F → Finset G.edgeSet) (colorings : Set (G.EdgeColoring Color))
    (x : G.edgeSet → Color) :
    x ∈ coloringGeneratorFamily faceBoundary colorings ↔
      ∃ C ∈ colorings, ∃ f : F, ∃ a b : Color,
        ValidColorPair a b ∧ x = polarizedFaceGenerator C a b (faceBoundary f) := by
  rfl

theorem coloringGeneratorFamily_mono {G : SimpleGraph V} {F : Type*}
    {faceBoundary : F → Finset G.edgeSet}
    {colorings₀ colorings₁ : Set (G.EdgeColoring Color)}
    (hsubset : colorings₀ ⊆ colorings₁) :
    coloringGeneratorFamily faceBoundary colorings₀ ⊆
      coloringGeneratorFamily faceBoundary colorings₁ := by
  rintro x ⟨C, hC, f, a, b, hab, rfl⟩
  exact ⟨C, hsubset hC, f, a, b, hab, rfl⟩

/-- The `𝔽₂`-subspace generated by an arbitrary coloring family. -/
noncomputable def coloringGeneratorSubspace {G : SimpleGraph V} {F : Type*}
    (faceBoundary : F → Finset G.edgeSet) (colorings : Set (G.EdgeColoring Color)) :
    Submodule F2 (G.edgeSet → Color) :=
  Submodule.span F2 (coloringGeneratorFamily faceBoundary colorings)

theorem coloringGeneratorSubspace_mono {G : SimpleGraph V} {F : Type*}
    {faceBoundary : F → Finset G.edgeSet}
    {colorings₀ colorings₁ : Set (G.EdgeColoring Color)}
    (hsubset : colorings₀ ⊆ colorings₁) :
    coloringGeneratorSubspace faceBoundary colorings₀ ≤
      coloringGeneratorSubspace faceBoundary colorings₁ :=
  Submodule.span_mono (coloringGeneratorFamily_mono hsubset)

/-- The existing closure-wide Definition 4.8 generator family is the special case where the
allowed colorings are exactly the edge-Kempe closure of the base coloring. -/
theorem kempeClosureGeneratorFamily_eq_coloringGeneratorFamily_edgeKempeClosure
    {G : SimpleGraph V} {F : Type*}
    (faceBoundary : F → Finset G.edgeSet) (C₀ : G.EdgeColoring Color) :
    kempeClosureGeneratorFamily faceBoundary C₀ =
      coloringGeneratorFamily faceBoundary (G.EdgeKempeClosure C₀) :=
  rfl

theorem kempeClosureGeneratorSubspace_eq_coloringGeneratorSubspace_edgeKempeClosure
    {G : SimpleGraph V} {F : Type*}
    (faceBoundary : F → Finset G.edgeSet) (C₀ : G.EdgeColoring Color) :
    kempeClosureGeneratorSubspace faceBoundary C₀ =
      coloringGeneratorSubspace faceBoundary (G.EdgeKempeClosure C₀) := by
  simp [kempeClosureGeneratorSubspace, coloringGeneratorSubspace,
    kempeClosureGeneratorFamily_eq_coloringGeneratorFamily_edgeKempeClosure]

/-- Boundary-erased Definition 4.8 generators coming from an arbitrary coloring family. -/
def projectedColoringGeneratorFamily
    {G : SimpleGraph V} (emb : PlaneEmbeddingWithBoundary G)
    (colorings : Set (G.EdgeColoring Color)) :
    Set (G.edgeSet → Color) :=
  (boundaryZeroProjection
    (selectedBoundarySupport emb.faceBoundary emb.faces emb.faces)) ''
      coloringGeneratorFamily emb.faceBoundary colorings

theorem mem_projectedColoringGeneratorFamily_iff
    {G : SimpleGraph V} {emb : PlaneEmbeddingWithBoundary G}
    {colorings : Set (G.EdgeColoring Color)} {x : G.edgeSet → Color} :
    x ∈ projectedColoringGeneratorFamily emb colorings ↔
      ∃ C ∈ colorings, ∃ f : emb.Face, ∃ a b : Color,
        ValidColorPair a b ∧
          x =
            boundaryZeroProjection
              (selectedBoundarySupport emb.faceBoundary emb.faces emb.faces)
              (polarizedFaceGenerator C a b (emb.faceBoundary f)) := by
  constructor
  · rintro ⟨y, hy, rfl⟩
    rcases (mem_coloringGeneratorFamily_iff emb.faceBoundary colorings y).1 hy with
      ⟨C, hC, f, a, b, hab, rfl⟩
    exact ⟨C, hC, f, a, b, hab, rfl⟩
  · rintro ⟨C, hC, f, a, b, hab, rfl⟩
    exact ⟨polarizedFaceGenerator C a b (emb.faceBoundary f),
      (mem_coloringGeneratorFamily_iff emb.faceBoundary colorings
        (polarizedFaceGenerator C a b (emb.faceBoundary f))).2
        ⟨C, hC, f, a, b, hab, rfl⟩,
      rfl⟩

/-- Boundary-erased generator span built from an arbitrary coloring family. -/
noncomputable def projectedColoringGeneratorSubspace
    {G : SimpleGraph V} (emb : PlaneEmbeddingWithBoundary G)
    (colorings : Set (G.EdgeColoring Color)) :
    Submodule F2 (G.edgeSet → Color) :=
  Submodule.map
    (boundaryZeroProjection
      (selectedBoundarySupport emb.faceBoundary emb.faces emb.faces))
    (coloringGeneratorSubspace emb.faceBoundary colorings)

theorem projectedColoringGeneratorSubspace_eq_span_projectedColoringGeneratorFamily
    {G : SimpleGraph V} (emb : PlaneEmbeddingWithBoundary G)
    (colorings : Set (G.EdgeColoring Color)) :
    projectedColoringGeneratorSubspace emb colorings =
      Submodule.span F2 (projectedColoringGeneratorFamily emb colorings) := by
  rw [projectedColoringGeneratorSubspace, projectedColoringGeneratorFamily,
    coloringGeneratorSubspace, Submodule.map_span]

theorem projectedColoringGeneratorSubspace_le_planarBoundaryZeroSubmodule
    {G : SimpleGraph V} (emb : PlaneEmbeddingWithBoundary G)
    (colorings : Set (G.EdgeColoring Color)) :
    projectedColoringGeneratorSubspace emb colorings ≤ planarBoundaryZeroSubmodule emb := by
  intro x hx
  rcases (Submodule.mem_map.mp hx) with ⟨y, _hy, rfl⟩
  exact boundaryZeroProjection_mem_boundaryZeroSubmodule y

theorem projectedColoringGeneratorSubspace_mono
    {G : SimpleGraph V} {emb : PlaneEmbeddingWithBoundary G}
    {colorings₀ colorings₁ : Set (G.EdgeColoring Color)}
    (hsubset : colorings₀ ⊆ colorings₁) :
    projectedColoringGeneratorSubspace emb colorings₀ ≤
      projectedColoringGeneratorSubspace emb colorings₁ := by
  intro x hx
  rcases (Submodule.mem_map.mp hx) with ⟨y, hy, rfl⟩
  exact Submodule.mem_map.mpr
    ⟨y, coloringGeneratorSubspace_mono hsubset hy, rfl⟩

theorem projectedKempeClosureGeneratorFamily_eq_projectedColoringGeneratorFamily_edgeKempeClosure
    {G : SimpleGraph V} (emb : PlaneEmbeddingWithBoundary G)
    (C₀ : G.EdgeColoring Color) :
    projectedKempeClosureGeneratorFamily emb C₀ =
      projectedColoringGeneratorFamily emb (G.EdgeKempeClosure C₀) := by
  ext x
  constructor
  · intro hx
    rcases (mem_projectedKempeClosureGeneratorFamily_iff
      (emb := emb) (C₀ := C₀)).1 hx with
      ⟨C, hC, f, a, b, hab, rfl⟩
    exact (mem_projectedColoringGeneratorFamily_iff
      (emb := emb) (colorings := G.EdgeKempeClosure C₀)).2
      ⟨C, hC, f, a, b, hab, rfl⟩
  · intro hx
    rcases (mem_projectedColoringGeneratorFamily_iff
      (emb := emb) (colorings := G.EdgeKempeClosure C₀)).1 hx with
      ⟨C, hC, f, a, b, hab, rfl⟩
    exact (mem_projectedKempeClosureGeneratorFamily_iff
      (emb := emb) (C₀ := C₀)).2
      ⟨C, hC, f, a, b, hab, rfl⟩

theorem projectedKempeClosureGeneratorSubspace_eq_projectedColoringGeneratorSubspace_edgeKempeClosure
    {G : SimpleGraph V} (emb : PlaneEmbeddingWithBoundary G) (C₀ : G.EdgeColoring Color) :
    projectedKempeClosureGeneratorSubspace emb C₀ =
      projectedColoringGeneratorSubspace emb (G.EdgeKempeClosure C₀) := by
  simp [projectedKempeClosureGeneratorSubspace, projectedColoringGeneratorSubspace,
    kempeClosureGeneratorSubspace_eq_coloringGeneratorSubspace_edgeKempeClosure]

/-- Detector version of the finite lab certificates for an arbitrary explicit coloring family:
every nonzero selected-boundary-zero chain pairs nontrivially with some projected generator
coming from that family. -/
def BoundaryZeroProjectedColoringGeneratorDetector {G : SimpleGraph V}
    [Fintype G.edgeSet]
    (emb : PlaneEmbeddingWithBoundary G)
    (colorings : Set (G.EdgeColoring Color)) : Prop :=
  ∀ ⦃z : G.edgeSet → Color⦄,
    z ∈ planarBoundaryZeroSubmodule emb →
    z ≠ 0 →
      ∃ p ∈ projectedColoringGeneratorSubspace emb colorings,
        chainDotBilinForm G.edgeSet p z ≠ 0

theorem BoundaryZeroProjectedColoringGeneratorDetector.mono
    {G : SimpleGraph V} [Fintype G.edgeSet]
    {emb : PlaneEmbeddingWithBoundary G}
    {colorings₀ colorings₁ : Set (G.EdgeColoring Color)}
    (hdet : BoundaryZeroProjectedColoringGeneratorDetector emb colorings₀)
    (hsubset : colorings₀ ⊆ colorings₁) :
    BoundaryZeroProjectedColoringGeneratorDetector emb colorings₁ := by
  intro z hzBoundary hzNonzero
  rcases hdet hzBoundary hzNonzero with ⟨p, hp, hpair⟩
  exact ⟨p, projectedColoringGeneratorSubspace_mono hsubset hp, hpair⟩

end Mettapedia.GraphTheory.FourColor
