import Mettapedia.GraphTheory.FourColor.Theorem49SpanningGap

namespace Mettapedia.GraphTheory.FourColor

open LinearMap

variable {V : Type*} [DecidableEq V]

/-- The actual `𝔽₂`-subspace generated by the Definition 4.8 Kempe-closure generator family. -/
noncomputable def kempeClosureGeneratorSubspace {G : SimpleGraph V} {F : Type*}
    (faceBoundary : F → Finset G.edgeSet) (C₀ : G.EdgeColoring Color) :
    Submodule F2 (G.edgeSet → Color) :=
  Submodule.span F2 (kempeClosureGeneratorFamily faceBoundary C₀)

/-- The global finite-chain dot product reduces to the existing restricted `chainDot` whenever the
right-hand chain vanishes off the chosen finite support. -/
theorem chainDotBilinForm_eq_chainDot_of_right_eq_zero_off {E : Type*}
    [Fintype E] [DecidableEq E] {S : Finset E} (x y : E → Color)
    (hy : ∀ e, e ∉ S → y e = 0) :
    chainDotBilinForm E x y = chainDot S x y := by
  classical
  rw [chainDotBilinForm_apply, chainDot]
  exact (Finset.sum_subset (Finset.subset_univ S) (by
    intro e _ he
    simp [hy e he])).symm

/-- The full finite-chain dot product against a purified face generator is the same as the
restricted dot product over that generator's bicolored boundary support. -/
theorem chainDotBilinForm_polarizedFaceGenerator_eq_chainDot {G : SimpleGraph V}
    [Fintype G.edgeSet] (C : G.EdgeColoring Color) (z : G.edgeSet → Color)
    (a b : Color) (faceBoundary : Finset G.edgeSet) :
    chainDotBilinForm G.edgeSet z (polarizedFaceGenerator C a b faceBoundary) =
      chainDot (boundaryBicoloredEdges C a b faceBoundary) z
        (polarizedFaceGenerator C a b faceBoundary) := by
  apply chainDotBilinForm_eq_chainDot_of_right_eq_zero_off
  intro e he
  exact indicatorChain_apply_of_not_mem (a + b) he

/-- Orthogonality to the span of the Definition 4.8 Kempe-closure generators implies the existing
route-facing generator-family annihilation predicate. -/
theorem annihilatesKempeClosureGeneratorFamily_of_mem_chainDot_orthogonal_kempeClosureGeneratorSubspace
    {G : SimpleGraph V} {F : Type*} [Fintype G.edgeSet]
    {faceBoundary : F → Finset G.edgeSet} {C₀ : G.EdgeColoring Color}
    {z : G.edgeSet → Color}
    (hz : z ∈ (chainDotBilinForm G.edgeSet).orthogonal
      (kempeClosureGeneratorSubspace faceBoundary C₀)) :
    AnnihilatesKempeClosureGeneratorFamily faceBoundary C₀ z := by
  intro C hC f a b hab
  let gen : G.edgeSet → Color := polarizedFaceGenerator C a b (faceBoundary f)
  have hgenMem : gen ∈ kempeClosureGeneratorSubspace faceBoundary C₀ := by
    exact Submodule.subset_span ⟨C, hC, f, a, b, hab, rfl⟩
  have horth : chainDotBilinForm G.edgeSet gen z = 0 := hz gen hgenMem
  have hfull : chainDotBilinForm G.edgeSet z gen = 0 := by
    calc
      chainDotBilinForm G.edgeSet z gen = chainDotBilinForm G.edgeSet gen z := by
        exact (chainDotBilinForm_isSymm G.edgeSet).eq z gen
      _ = 0 := horth
  simpa [gen, chainDotBilinForm_polarizedFaceGenerator_eq_chainDot C z a b (faceBoundary f)]
    using hfull

/-- The converse generator-span direction: the route-facing annihilation predicate is exactly
orthogonality to the actual span of Definition 4.8 generators. -/
theorem mem_chainDot_orthogonal_kempeClosureGeneratorSubspace_of_annihilatesKempeClosureGeneratorFamily
    {G : SimpleGraph V} {F : Type*} [Fintype G.edgeSet]
    {faceBoundary : F → Finset G.edgeSet} {C₀ : G.EdgeColoring Color}
    {z : G.edgeSet → Color}
    (hz : AnnihilatesKempeClosureGeneratorFamily faceBoundary C₀ z) :
    z ∈ (chainDotBilinForm G.edgeSet).orthogonal
      (kempeClosureGeneratorSubspace faceBoundary C₀) := by
  intro x hx
  change chainDotBilinForm G.edgeSet x z = 0
  refine Submodule.span_induction (s := kempeClosureGeneratorFamily faceBoundary C₀)
    (fun gen hgen => ?_) ?_ ?_ ?_ hx
  ·
    rcases (mem_kempeClosureGeneratorFamily_iff faceBoundary C₀ gen).1 hgen with
      ⟨C, hC, f, a, b, hab, rfl⟩
    have hfull :
        chainDotBilinForm G.edgeSet z (polarizedFaceGenerator C a b (faceBoundary f)) = 0 := by
      simpa [chainDotBilinForm_polarizedFaceGenerator_eq_chainDot C z a b (faceBoundary f)]
        using hz C hC f a b hab
    calc
      chainDotBilinForm G.edgeSet (polarizedFaceGenerator C a b (faceBoundary f)) z =
          chainDotBilinForm G.edgeSet z (polarizedFaceGenerator C a b (faceBoundary f)) := by
            exact (chainDotBilinForm_isSymm G.edgeSet).eq
              (polarizedFaceGenerator C a b (faceBoundary f)) z
      _ = 0 := hfull
  · simp
  · intro x y hx hy hxOrth hyOrth
    simp [hxOrth, hyOrth]
  · intro a x hx hxOrth
    simp [hxOrth]

/-- Constructor for the concrete Theorem 4.9 submodule bridge with the generator side fixed to
the actual span of the Definition 4.8 Kempe-closure generator family.  The remaining algebraic
inputs are now the target difference subspace, span containment, and boundary vanishing. -/
noncomputable def Theorem49SubmoduleDualityData.ofKempeGeneratorSubspace
    {G : SimpleGraph V} {emb : PlaneEmbeddingWithBoundary G} {C₀ : G.EdgeColoring Color}
    [Fintype G.edgeSet]
    (differenceSubspace : Submodule F2 (G.edgeSet → Color))
    (hle : kempeClosureGeneratorSubspace emb.faceBoundary C₀ ≤ differenceSubspace)
    (hboundary :
      ∀ ⦃z : G.edgeSet → Color⦄,
        z ∈ differenceSubspace →
          ∀ e ∈ selectedBoundarySupport emb.faceBoundary emb.faces emb.faces, z e = 0) :
    Theorem49SubmoduleDualityData emb C₀ :=
  Theorem49SubmoduleDualityData.ofChainDot
    differenceSubspace (kempeClosureGeneratorSubspace emb.faceBoundary C₀)
    hle hboundary
    (by
      intro z hz
      exact
        annihilatesKempeClosureGeneratorFamily_of_mem_chainDot_orthogonal_kempeClosureGeneratorSubspace
          (faceBoundary := emb.faceBoundary) (C₀ := C₀) (z := z) hz)

/-- Theorem 4.9 spanning conclusion with both the standard chain dot product and the generator
subspace fixed canonically.  The remaining obligations are precisely the v23 target subspace,
containment of the Kempe-generator span in it, and selected-boundary vanishing for its elements. -/
theorem theorem49_kempeGeneratorSubspace_spanning_of_planarBoundaryInteriorDualBoundaryRootAdjDistancePeelData
    {G : SimpleGraph V}
    [Fintype G.edgeSet] [FiniteDimensional F2 (G.edgeSet → Color)]
    (emb : PlaneEmbeddingWithBoundary G)
    (data : PlanarBoundaryInteriorDualBoundaryRootAdjDistancePeelData emb)
    (C₀ : G.EdgeColoring Color) (hC₀ : IsTaitEdgeColoring G C₀)
    (differenceSubspace : Submodule F2 (G.edgeSet → Color))
    (hle : kempeClosureGeneratorSubspace emb.faceBoundary C₀ ≤ differenceSubspace)
    (hboundary :
      ∀ ⦃z : G.edgeSet → Color⦄,
        z ∈ differenceSubspace →
          ∀ e ∈ selectedBoundarySupport emb.faceBoundary emb.faces emb.faces, z e = 0) :
    kempeClosureGeneratorSubspace emb.faceBoundary C₀ = differenceSubspace :=
  theorem49_submodule_spanning_of_planarBoundaryInteriorDualBoundaryRootAdjDistancePeelData
    emb data C₀ hC₀
    (Theorem49SubmoduleDualityData.ofKempeGeneratorSubspace differenceSubspace hle hboundary)

/-- The canonical Kempe-generator subspace spans the target difference subspace as soon as the
same embedding carries boundary-aware height-ordered witness-cover data and the target subspace
has the expected boundary-zero interpretation. -/
theorem theorem49_kempeGeneratorSubspace_spanning_of_planarBoundaryHeightOrderedFacePeelWitnessData
    {G : SimpleGraph V}
    [Fintype G.edgeSet] [FiniteDimensional F2 (G.edgeSet → Color)]
    (emb : PlaneEmbeddingWithBoundary G)
    (data : PlanarBoundaryHeightOrderedFacePeelWitnessData emb)
    (C₀ : G.EdgeColoring Color) (hC₀ : IsTaitEdgeColoring G C₀)
    (differenceSubspace : Submodule F2 (G.edgeSet → Color))
    (hle : kempeClosureGeneratorSubspace emb.faceBoundary C₀ ≤ differenceSubspace)
    (hboundary :
      ∀ ⦃z : G.edgeSet → Color⦄,
        z ∈ differenceSubspace →
          ∀ e ∈ selectedBoundarySupport emb.faceBoundary emb.faces emb.faces, z e = 0) :
    kempeClosureGeneratorSubspace emb.faceBoundary C₀ = differenceSubspace :=
  theorem49_submodule_spanning_of_planarBoundaryHeightOrderedFacePeelWitnessData
    emb data C₀ hC₀
    (Theorem49SubmoduleDualityData.ofKempeGeneratorSubspace differenceSubspace hle hboundary)

/-- Finite-collar version of the canonical Kempe-generator spanning bridge. -/
theorem theorem49_kempeGeneratorSubspace_spanning_of_planarBoundaryCollarLayerFacePeelWitnessData
    {G : SimpleGraph V}
    [Fintype G.edgeSet] [FiniteDimensional F2 (G.edgeSet → Color)]
    (emb : PlaneEmbeddingWithBoundary G)
    (data : PlanarBoundaryCollarLayerFacePeelWitnessData emb)
    (C₀ : G.EdgeColoring Color) (hC₀ : IsTaitEdgeColoring G C₀)
    (differenceSubspace : Submodule F2 (G.edgeSet → Color))
    (hle : kempeClosureGeneratorSubspace emb.faceBoundary C₀ ≤ differenceSubspace)
    (hboundary :
      ∀ ⦃z : G.edgeSet → Color⦄,
        z ∈ differenceSubspace →
          ∀ e ∈ selectedBoundarySupport emb.faceBoundary emb.faces emb.faces, z e = 0) :
    kempeClosureGeneratorSubspace emb.faceBoundary C₀ = differenceSubspace :=
  theorem49_submodule_spanning_of_planarBoundaryCollarLayerFacePeelWitnessData
    emb data C₀ hC₀
    (Theorem49SubmoduleDualityData.ofKempeGeneratorSubspace differenceSubspace hle hboundary)

/-- Graph-level height-ordered spanning bridge with the generator side fixed to the actual
Definition 4.8 Kempe-closure generator subspace.  Compared with the more generic chain-dot
wrapper, the orthogonality-to-annihilator field of `Theorem49SubmoduleDualityData` is now supplied
by the canonical generator-span theorem itself; callers only provide the target subspace,
containment, and boundary-vanishing interpretation. -/
theorem exists_theorem49_kempeGeneratorSubspace_spanning_of_admitsPlanarBoundaryHeightOrderedFacePeelWitnessData
    {G : SimpleGraph V}
    [Fintype G.edgeSet] [FiniteDimensional F2 (G.edgeSet → Color)]
    (hG : AdmitsPlanarBoundaryHeightOrderedFacePeelWitnessData G)
    (C₀ : G.EdgeColoring Color) (hC₀ : IsTaitEdgeColoring G C₀)
    (differenceSubspaceOf : ∀ emb : PlaneEmbeddingWithBoundary G,
      PlanarBoundaryHeightOrderedFacePeelWitnessData emb → Submodule F2 (G.edgeSet → Color))
    (hle : ∀ emb : PlaneEmbeddingWithBoundary G,
      ∀ data : PlanarBoundaryHeightOrderedFacePeelWitnessData emb,
        kempeClosureGeneratorSubspace emb.faceBoundary C₀ ≤ differenceSubspaceOf emb data)
    (hboundary : ∀ emb : PlaneEmbeddingWithBoundary G,
      ∀ data : PlanarBoundaryHeightOrderedFacePeelWitnessData emb,
        ∀ ⦃z : G.edgeSet → Color⦄,
          z ∈ differenceSubspaceOf emb data →
            ∀ e ∈ selectedBoundarySupport emb.faceBoundary emb.faces emb.faces, z e = 0) :
    ∃ emb : PlaneEmbeddingWithBoundary G,
      ∃ data : PlanarBoundaryHeightOrderedFacePeelWitnessData emb,
        kempeClosureGeneratorSubspace emb.faceBoundary C₀ = differenceSubspaceOf emb data := by
  rcases hG with ⟨emb, ⟨data⟩⟩
  exact
    ⟨emb, data,
      theorem49_kempeGeneratorSubspace_spanning_of_planarBoundaryHeightOrderedFacePeelWitnessData
        emb data C₀ hC₀ (differenceSubspaceOf emb data) (hle emb data)
        (hboundary emb data)⟩

/-- Graph-level finite-collar version of the canonical Definition 4.8 generator-subspace
spanning bridge. -/
theorem exists_theorem49_kempeGeneratorSubspace_spanning_of_admitsPlanarBoundaryCollarLayerFacePeelWitnessData
    {G : SimpleGraph V}
    [Fintype G.edgeSet] [FiniteDimensional F2 (G.edgeSet → Color)]
    (hG : AdmitsPlanarBoundaryCollarLayerFacePeelWitnessData G)
    (C₀ : G.EdgeColoring Color) (hC₀ : IsTaitEdgeColoring G C₀)
    (differenceSubspaceOf : ∀ emb : PlaneEmbeddingWithBoundary G,
      PlanarBoundaryCollarLayerFacePeelWitnessData emb → Submodule F2 (G.edgeSet → Color))
    (hle : ∀ emb : PlaneEmbeddingWithBoundary G,
      ∀ data : PlanarBoundaryCollarLayerFacePeelWitnessData emb,
        kempeClosureGeneratorSubspace emb.faceBoundary C₀ ≤ differenceSubspaceOf emb data)
    (hboundary : ∀ emb : PlaneEmbeddingWithBoundary G,
      ∀ data : PlanarBoundaryCollarLayerFacePeelWitnessData emb,
        ∀ ⦃z : G.edgeSet → Color⦄,
          z ∈ differenceSubspaceOf emb data →
            ∀ e ∈ selectedBoundarySupport emb.faceBoundary emb.faces emb.faces, z e = 0) :
    ∃ emb : PlaneEmbeddingWithBoundary G,
      ∃ data : PlanarBoundaryCollarLayerFacePeelWitnessData emb,
        kempeClosureGeneratorSubspace emb.faceBoundary C₀ = differenceSubspaceOf emb data := by
  rcases hG with ⟨emb, ⟨data⟩⟩
  exact
    ⟨emb, data,
      theorem49_kempeGeneratorSubspace_spanning_of_planarBoundaryCollarLayerFacePeelWitnessData
        emb data C₀ hC₀ (differenceSubspaceOf emb data) (hle emb data)
        (hboundary emb data)⟩

end Mettapedia.GraphTheory.FourColor
