/-
Copyright (c) 2026 Mettapedia Authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Mettapedia Project
-/
import Mathlib.MeasureTheory.Measure.MeasureSpace
import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
import Mathlib.MeasureTheory.Function.SimpleFunc
import Mathlib.MeasureTheory.Integral.IntegrableOn
import Mathlib.Probability.Independence.Basic
import Mathlib.Probability.Independence.Integration
import Mathlib.Probability.Independence.InfinitePi
import Mathlib.Probability.Moments.Variance
import Mathlib.Probability.ProductMeasure
import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.Analysis.Convex.Integral
import Mathlib.Analysis.Convex.Continuous
import Mathlib.Analysis.MeanInequalities

/-!
# Billingsley Chapter 1, Section 5: Simple Random Variables

This file formalizes Section 5 of Billingsley's "Probability and Measure" (3rd Edition),
which covers simple random variables and their expected values.

## Main concepts

* Simple random variables: measurable functions with finite range
* Generated σ-field σ(X₁,...,Xₙ)
* Expected value E[X]
* Variance Var[X]
* Convergence: almost surely and in probability
* Independence of random variables
* Standard inequalities: Markov, Chebyshev, Jensen, Hölder, Schwarz

## Main theorems

* Theorem 5.1: σ-field generated by random variables
* Theorem 5.2: Convergence with probability 1 implies convergence in probability
* Theorem 5.3: Existence of independent sequences (uses unit interval construction)
* Theorem 5.4: Dominated convergence for uniformly bounded sequences

## Notes

In mathlib:
- Simple functions are `MeasureTheory.SimpleFunc`
- Expected value is `∫ x, f x ∂μ` (Bochner integral)
- Independence is `ProbabilityTheory.iIndepFun`

## References

* [Billingsley, *Probability and Measure* (3rd ed.), Section 5][billingsley1995]
-/

noncomputable section

open MeasureTheory Set Filter Topology ProbabilityTheory
open scoped ENNReal NNReal

namespace Mettapedia.AutoBooks.Billingsley.Ch01Sec05

variable {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω) [IsProbabilityMeasure μ]

/-! ## Simple Random Variables

A simple random variable has finite range and is measurable.
In mathlib, this is `SimpleFunc Ω ℝ`.
-/

/-- A simple random variable in the sense of Billingsley is a `SimpleFunc`. -/
abbrev SimpleRV (Ω : Type*) [MeasurableSpace Ω] := SimpleFunc Ω ℝ

/-! ## Expected Value

For simple random variables, E[X] = Σₓ x · P[X = x].
In mathlib, this is the integral `∫ x, f x ∂μ`.
-/

/-- E[I_A] = P(A). Billingsley's (5.17).
See `MeasureTheory.integral_indicator` in mathlib. -/
theorem expected_indicator (A : Set Ω) (hA : MeasurableSet A) :
    ∫ ω, (A.indicator (1 : Ω → ℝ)) ω ∂μ = (μ A).toReal := by
  rw [integral_indicator hA]
  simp only [Pi.one_apply, integral_const, smul_eq_mul, mul_one]
  rw [measureReal_restrict_apply_univ, measureReal_def]

/-- E[a] = a for constants. Billingsley's (5.18).
See `MeasureTheory.integral_const` in mathlib. -/
theorem expected_const (a : ℝ) : ∫ _ : Ω, a ∂μ = a := by
  simp only [integral_const, measure_univ, smul_eq_mul]
  norm_num

/-- Linearity of expected value: E[αX + βY] = αE[X] + βE[Y]. Billingsley's (5.21).
See `integral_add` and `integral_smul` in mathlib. -/
theorem expected_linear (X Y : Ω → ℝ) (hX : Integrable X μ) (hY : Integrable Y μ)
    (α β : ℝ) :
    ∫ ω, (α * X ω + β * Y ω) ∂μ = α * ∫ ω, X ω ∂μ + β * ∫ ω, Y ω ∂μ := by
  rw [integral_add (hX.const_mul α) (hY.const_mul β)]
  rw [integral_const_mul α X, integral_const_mul β Y]

/-- Order preservation: X ≤ Y implies E[X] ≤ E[Y]. Billingsley's (5.22). -/
theorem expected_mono {X Y : Ω → ℝ} (hX : Integrable X μ) (hY : Integrable Y μ)
    (h : ∀ ω, X ω ≤ Y ω) : ∫ ω, X ω ∂μ ≤ ∫ ω, Y ω ∂μ :=
  integral_mono hX hY h

/-- Triangle inequality: |E[X]| ≤ E[|X|]. Billingsley's (5.23). -/
theorem expected_abs_le {X : Ω → ℝ} (hX : Integrable X μ) :
    |∫ ω, X ω ∂μ| ≤ ∫ ω, |X ω| ∂μ :=
  norm_integral_le_integral_norm X

/-! ## Variance

Var[X] = E[(X - E[X])²] = E[X²] - E[X]².
-/

/-- Variance of a random variable. Billingsley's (5.26).
Var[X] = E[(X - E[X])²]. -/
def varianceSimple (X : Ω → ℝ) : ℝ :=
  ∫ ω, (X ω - ∫ ω', X ω' ∂μ)^2 ∂μ

/-- Variance scaling: Var[aX + b] = a² Var[X]. Billingsley's (5.27). -/
theorem variance_affine (X : Ω → ℝ) (a b : ℝ) (hX : Integrable X μ)
    (_hX2 : Integrable (fun ω => (X ω)^2) μ) :
    varianceSimple μ (fun ω => a * X ω + b) = a^2 * varianceSimple μ X := by
  -- E[(aX + b - E[aX + b])²] = E[(a(X - E[X]))²] = a²E[(X - E[X])²]
  unfold varianceSimple
  -- E[aX + b] = a * E[X] + b by linearity
  have hE : ∫ ω', (a * X ω' + b) ∂μ = a * ∫ ω', X ω' ∂μ + b := by
    rw [integral_add (hX.const_mul a) (integrable_const b)]
    rw [integral_const_mul, integral_const]
    simp only [smul_eq_mul, measureReal_def, measure_univ, ENNReal.toReal_one, one_mul]
  -- Rewrite (aX + b) - E[aX + b] = a * (X - E[X])
  have hDiff : ∀ ω, (a * X ω + b) - (a * ∫ ω', X ω' ∂μ + b) = a * (X ω - ∫ ω', X ω' ∂μ) := by
    intro ω; ring
  conv_lhs =>
    arg 2
    ext ω
    rw [hE, hDiff ω, mul_pow]
  -- Factor out a²
  rw [integral_const_mul]

/-- Product rule for independent random variables: E[XY] = E[X]·E[Y].
Billingsley's (5.25) for two variables. -/
theorem expected_prod_indep_pair {X Y : Ω → ℝ}
    (hX : Integrable X μ) (hY : Integrable Y μ)
    (_hXY : Integrable (fun ω => X ω * Y ω) μ)
    (hIndep : IndepFun X Y μ) :
    ∫ ω, X ω * Y ω ∂μ = (∫ ω, X ω ∂μ) * (∫ ω, Y ω ∂μ) := by
  exact hIndep.integral_fun_mul_eq_mul_integral hX.aestronglyMeasurable hY.aestronglyMeasurable

/-- Variance of sum of independent RVs: Var[X + Y] = Var[X] + Var[Y].
From Billingsley's (5.28). -/
theorem variance_sum_indep_pair {X Y : Ω → ℝ}
    (hX : Integrable X μ) (hY : Integrable Y μ)
    (hX2 : Integrable (fun ω => (X ω)^2) μ) (hY2 : Integrable (fun ω => (Y ω)^2) μ)
    (hIndep : IndepFun X Y μ) :
    varianceSimple μ (fun ω => X ω + Y ω) =
      varianceSimple μ X + varianceSimple μ Y := by
  have hXmemLp : MemLp X 2 μ :=
    (memLp_two_iff_integrable_sq hX.aestronglyMeasurable).mpr hX2
  have hYmemLp : MemLp Y 2 μ :=
    (memLp_two_iff_integrable_sq hY.aestronglyMeasurable).mpr hY2
  have hXmeas : AEMeasurable X μ := hX.aemeasurable
  have hYmeas : AEMeasurable Y μ := hY.aemeasurable
  have hXYmeas : AEMeasurable (fun ω => X ω + Y ω) μ := hXmeas.add hYmeas
  have eqX : varianceSimple μ X = ProbabilityTheory.variance X μ :=
    (ProbabilityTheory.variance_eq_integral hXmeas).symm
  have eqY : varianceSimple μ Y = ProbabilityTheory.variance Y μ :=
    (ProbabilityTheory.variance_eq_integral hYmeas).symm
  have eqXY : varianceSimple μ (fun ω => X ω + Y ω) =
      ProbabilityTheory.variance (fun ω => X ω + Y ω) μ :=
    (ProbabilityTheory.variance_eq_integral hXYmeas).symm
  rw [eqX, eqY, eqXY]
  exact hIndep.variance_fun_add hXmemLp hYmemLp

/-! ## Convergence -/

/-- Almost sure convergence: Xₙ → X a.s. means P[lim Xₙ = X] = 1. -/
def ConvergesAeToFun {α : Type*} [MeasurableSpace α] (X : ℕ → α → ℝ) (Y : α → ℝ)
    (μ' : Measure α) : Prop :=
  ∀ᵐ ω ∂μ', Filter.Tendsto (fun n => X n ω) Filter.atTop (nhds (Y ω))

/-- Convergence in probability: Xₙ →ᵖ X means P[|Xₙ - X| > ε] → 0 for all ε > 0. -/
def ConvergesInProbability {α : Type*} [MeasurableSpace α] (X : ℕ → α → ℝ) (Y : α → ℝ)
    (μ' : Measure α) : Prop :=
  ∀ ε > 0, Filter.Tendsto (fun n => μ' {ω | ε < |X n ω - Y ω|}) Filter.atTop (nhds 0)

/-- Theorem 5.2(ii): Almost sure convergence implies convergence in probability. -/
theorem ae_tendsto_imp_prob_tendsto {X : ℕ → Ω → ℝ} {Y : Ω → ℝ}
    (hX_meas : ∀ n, Measurable (X n))
    (h : ConvergesAeToFun X Y μ) : ConvergesInProbability X Y μ := by
  intro ε hε
  have hf : ∀ n, AEStronglyMeasurable (X n) μ :=
    fun n => (hX_meas n).aestronglyMeasurable
  have hTIM : TendstoInMeasure μ X atTop Y :=
    tendstoInMeasure_of_tendsto_ae hf h
  have hTIM' := (tendstoInMeasure_iff_dist.mp hTIM) ε hε
  have hsub : ∀ n, μ {ω | ε < |X n ω - Y ω|} ≤ μ {ω | ε ≤ dist (X n ω) (Y ω)} := by
    intro n
    refine measure_mono (fun ω hω => ?_)
    simp only [mem_setOf_eq, Real.dist_eq] at hω ⊢
    exact le_of_lt hω
  refine tendsto_of_tendsto_of_tendsto_of_le_of_le tendsto_const_nhds hTIM' ?_ ?_
  · intro n; exact zero_le _
  · exact hsub

/-- Theorem 5.2(i): Convergence with probability 1 iff P[|Xₙ - X| ≥ ε i.o.] = 0
for all ε > 0. -/
theorem ae_convergence_iff_limsup_null {X : ℕ → Ω → ℝ} {Y : Ω → ℝ}
    (_hX : ∀ n, Measurable (X n)) (_hY : Measurable Y) :
    ConvergesAeToFun X Y μ ↔
      ∀ ε > 0, μ (Filter.limsup (fun n => {ω | ε ≤ |X n ω - Y ω|}) Filter.atTop) = 0 := by
  unfold ConvergesAeToFun
  rw [ae_iff]
  constructor
  · intro h ε hε
    refine measure_mono_null ?_ h
    intro ω hω
    rw [Filter.mem_limsup_iff_frequently_mem] at hω
    simp only [Set.mem_setOf_eq]
    intro hTendsto
    have hEv : ∀ᶠ n in Filter.atTop, |X n ω - Y ω| < ε := by
      rw [Metric.tendsto_atTop] at hTendsto
      obtain ⟨N, hN⟩ := hTendsto ε hε
      refine Filter.eventually_atTop.mpr ⟨N, fun n hn => ?_⟩
      have := hN n hn
      rwa [Real.dist_eq] at this
    have hContra := hω.and_eventually hEv
    rcases hContra.exists with ⟨n, h1, h2⟩
    exact (not_lt.mpr h1) h2
  · intro h
    set E : ℕ → Set Ω := fun k =>
      Filter.limsup (fun n => {ω | (1:ℝ)/(k+1) ≤ |X n ω - Y ω|}) Filter.atTop
    have hEnull : ∀ k, μ (E k) = 0 := by
      intro k
      apply h
      positivity
    have hUnion : μ (⋃ k, E k) = 0 := measure_iUnion_null hEnull
    refine measure_mono_null ?_ hUnion
    intro ω hω
    simp only [Set.mem_setOf_eq] at hω
    simp only [Set.mem_iUnion]
    by_contra hAll
    push_neg at hAll
    apply hω
    rw [Metric.tendsto_atTop]
    intro ε hε
    obtain ⟨k, hk⟩ := exists_nat_one_div_lt hε
    have hNotIn : ω ∉ E k := hAll k
    simp only [E, Filter.mem_limsup_iff_frequently_mem, Filter.not_frequently,
      Filter.eventually_atTop] at hNotIn
    obtain ⟨N, hN⟩ := hNotIn
    refine ⟨N, fun n hn => ?_⟩
    have := hN n hn
    simp only [Set.mem_setOf_eq, not_le] at this
    rw [Real.dist_eq]
    exact lt_trans this hk

/-! ## Theorem 5.4: Dominated Convergence for Uniformly Bounded Sequences -/

/-- Theorem 5.4: If {Xₙ} is uniformly bounded and Xₙ → X a.s., then E[Xₙ] → E[X].
This is a special case of Lebesgue's dominated convergence theorem.
See `tendsto_integral_of_dominated_convergence` in mathlib. -/
theorem expected_limit_of_bounded_ae_tendsto {X : ℕ → Ω → ℝ} {Y : Ω → ℝ}
    (hX_meas : ∀ n, Measurable (X n)) (_hY_meas : Measurable Y)
    (K : ℝ) (hK : ∀ n ω, |X n ω| ≤ K)
    (h_ae : ConvergesAeToFun X Y μ) :
    Filter.Tendsto (fun n => ∫ ω, X n ω ∂μ) Filter.atTop (nhds (∫ ω, Y ω ∂μ)) := by
  refine tendsto_integral_of_dominated_convergence (fun _ => K) ?_ ?_ ?_ ?_
  · intro n; exact (hX_meas n).aestronglyMeasurable
  · exact integrable_const K
  · intro n
    filter_upwards with ω
    rw [Real.norm_eq_abs]
    exact hK n ω
  · exact h_ae

/-! ## Standard Inequalities -/

/-- Markov's inequality: P[|X| ≥ a] ≤ E[|X|] / a. Billingsley's (5.30)/(5.31). -/
theorem markov_inequality {X : Ω → ℝ} (hX : Integrable X μ) {a : ℝ} (ha : 0 < a) :
    (μ {ω | a ≤ |X ω|}).toReal ≤ (∫ ω, |X ω| ∂μ) / a := by
  -- Use mathlib's mul_meas_ge_le_integral_of_nonneg
  have h_nonneg : 0 ≤ᵐ[μ] fun ω => |X ω| := by
    filter_upwards with ω using abs_nonneg (X ω)
  have h_int_abs : Integrable (fun ω => |X ω|) μ := hX.abs
  have hkey := mul_meas_ge_le_integral_of_nonneg h_nonneg h_int_abs a
  -- hkey: a * μ.real {ω | a ≤ |X ω|} ≤ ∫ ω, |X ω| ∂μ
  -- Convert μ.real to (μ _).toReal
  rw [measureReal_def] at hkey
  -- Divide both sides by a
  have ha_ne : a ≠ 0 := ne_of_gt ha
  calc (μ {ω | a ≤ |X ω|}).toReal
      = a * (μ {ω | a ≤ |X ω|}).toReal / a := by field_simp
    _ ≤ (∫ ω, |X ω| ∂μ) / a := by
        apply div_le_div_of_nonneg_right hkey (le_of_lt ha)

/-- Chebyshev's inequality: P[|X - m| ≥ a] ≤ Var[X] / a². Billingsley's (5.32). -/
theorem chebyshev_inequality {X : Ω → ℝ} (hX : Integrable X μ)
    (hX2 : Integrable (fun ω => (X ω)^2) μ) {a : ℝ} (ha : 0 < a) :
    (μ {ω | a ≤ |X ω - ∫ ω', X ω' ∂μ|}).toReal ≤ varianceSimple μ X / a^2 := by
  -- Chebyshev follows from Markov applied to (X - m)²
  -- P[|X - m| ≥ a] = P[(X - m)² ≥ a²] ≤ E[(X - m)²] / a² = Var[X] / a²
  set m := ∫ ω', X ω' ∂μ with hm_def
  set Y := fun ω => X ω - m with hY_def
  -- {|Y| ≥ a} = {Y² ≥ a²}
  have h_set_eq : {ω | a ≤ |Y ω|} = {ω | a^2 ≤ (Y ω)^2} := by
    ext ω
    simp only [mem_setOf_eq, ← sq_abs (Y ω)]
    constructor
    · intro h
      have h1 : -|Y ω| ≤ a := (neg_nonpos.mpr (abs_nonneg _)).trans (le_of_lt ha)
      exact sq_le_sq' h1 h
    · intro h
      have := Real.sqrt_le_sqrt h
      rw [Real.sqrt_sq (le_of_lt ha), Real.sqrt_sq_eq_abs, abs_abs] at this
      exact this
  rw [h_set_eq]
  -- Y is integrable
  have hY : Integrable Y μ := hX.sub (integrable_const m)
  -- Y² is integrable since X² is integrable and (X - const)² bounded by 2(X² + const²)
  have hY2 : Integrable (fun ω => (Y ω)^2) μ := by
    -- (X - m)² = X² - 2mX + m²
    have : (fun ω => (Y ω)^2) = fun ω => (X ω)^2 - 2 * m * X ω + m^2 := by
      ext ω; ring
    rw [this]
    exact (hX2.sub (hX.const_mul (2 * m))).add (integrable_const (m^2))
  -- Apply Markov to Y² with threshold a²
  have ha2 : 0 < a^2 := sq_pos_of_pos ha
  have hMarkov := markov_inequality μ hY2 ha2
  -- |Y²| = Y² since Y² ≥ 0
  have h_abs_sq : ∫ ω, |(Y ω)^2| ∂μ = ∫ ω, (Y ω)^2 ∂μ := by
    congr 1 with ω; exact abs_of_nonneg (sq_nonneg (Y ω))
  rw [h_abs_sq] at hMarkov
  -- Convert {a² ≤ |Y²|} to {a² ≤ Y²}
  have h_set_abs : {ω | a^2 ≤ |(Y ω)^2|} = {ω | a^2 ≤ (Y ω)^2} := by
    ext ω; simp only [mem_setOf_eq, abs_of_nonneg (sq_nonneg (Y ω))]
  rw [h_set_abs] at hMarkov
  -- Variance = E[Y²]
  have hVar : varianceSimple μ X = ∫ ω, (Y ω)^2 ∂μ := rfl
  simp only [hVar, sq] at hMarkov ⊢
  exact hMarkov

/-- Jensen's inequality: φ(E[X]) ≤ E[φ(X)] for convex φ. Billingsley's (5.33). -/
theorem jensen_inequality {X : Ω → ℝ} (hX : Integrable X μ)
    {φ : ℝ → ℝ} (hφ : ConvexOn ℝ Set.univ φ) (hφ_int : Integrable (φ ∘ X) μ) :
    φ (∫ ω, X ω ∂μ) ≤ ∫ ω, φ (X ω) ∂μ := by
  refine hφ.map_integral_le (hφ.continuousOn isOpen_univ) isClosed_univ ?_ hX hφ_int
  filter_upwards with ω using Set.mem_univ _

/-- Schwarz inequality (Cauchy-Schwarz): E[|XY|]² ≤ E[X²] · E[Y²].
Billingsley's (5.36). -/
theorem schwarz_inequality {X Y : Ω → ℝ}
    (hXm : AEStronglyMeasurable X μ) (hYm : AEStronglyMeasurable Y μ)
    (hX : Integrable (fun ω => (X ω)^2) μ) (hY : Integrable (fun ω => (Y ω)^2) μ) :
    (∫ ω, |X ω * Y ω| ∂μ)^2 ≤ (∫ ω, (X ω)^2 ∂μ) * (∫ ω, (Y ω)^2 ∂μ) := by
  have hXlp : MemLp X 2 μ := (memLp_two_iff_integrable_sq hXm).mpr hX
  have hYlp : MemLp Y 2 μ := (memLp_two_iff_integrable_sq hYm).mpr hY
  have h2eq : ENNReal.ofReal (2 : ℝ) = 2 := by simp
  have hXlp' : MemLp X (ENNReal.ofReal 2) μ := by rw [h2eq]; exact hXlp
  have hYlp' : MemLp Y (ENNReal.ofReal 2) μ := by rw [h2eq]; exact hYlp
  have hpq : (2 : ℝ).HolderConjugate 2 := Real.HolderConjugate.two_two
  have hMain := integral_mul_norm_le_Lp_mul_Lq (μ := μ) hpq hXlp' hYlp'
  have hBint : ∫ a, ‖X a‖ ^ (2:ℝ) ∂μ = ∫ a, (X a) ^ 2 ∂μ := by
    refine integral_congr_ae ?_
    filter_upwards with a
    rw [Real.rpow_two, Real.norm_eq_abs, sq_abs]
  have hCint : ∫ a, ‖Y a‖ ^ (2:ℝ) ∂μ = ∫ a, (Y a) ^ 2 ∂μ := by
    refine integral_congr_ae ?_
    filter_upwards with a
    rw [Real.rpow_two, Real.norm_eq_abs, sq_abs]
  have hAint : ∫ a, ‖X a‖ * ‖Y a‖ ∂μ = ∫ a, |X a * Y a| ∂μ := by
    refine integral_congr_ae ?_
    filter_upwards with a
    rw [Real.norm_eq_abs, Real.norm_eq_abs, ← abs_mul]
  rw [hBint, hCint, hAint] at hMain
  set B := ∫ a, (X a)^2 ∂μ
  set C := ∫ a, (Y a)^2 ∂μ
  set A := ∫ a, |X a * Y a| ∂μ
  have hBnn : 0 ≤ B := integral_nonneg (fun _ => sq_nonneg _)
  have hCnn : 0 ≤ C := integral_nonneg (fun _ => sq_nonneg _)
  have hAnn : 0 ≤ A := integral_nonneg (fun _ => abs_nonneg _)
  have hA_sq_le : A^2 ≤ (B^((1:ℝ)/2) * C^((1:ℝ)/2))^2 :=
    pow_le_pow_left₀ hAnn hMain 2
  rw [mul_pow] at hA_sq_le
  have hhalf : (1 : ℝ)/2 = ((2 : ℕ) : ℝ)⁻¹ := by norm_num
  have hB_sqr : (B^((1:ℝ)/2))^2 = B := by
    rw [hhalf]
    exact Real.rpow_inv_natCast_pow hBnn (by norm_num)
  have hC_sqr : (C^((1:ℝ)/2))^2 = C := by
    rw [hhalf]
    exact Real.rpow_inv_natCast_pow hCnn (by norm_num)
  rw [hB_sqr, hC_sqr] at hA_sq_le
  exact hA_sq_le

/-! ## Theorem 5.1: σ-field Generated by Random Variables -/

/-- Theorem 5.1(i): σ(X₁,...,Xₙ) consists of sets [(X₁,...,Xₙ) ∈ H] for H ⊆ ℝⁿ. -/
theorem generated_sigma_field_simple {n : ℕ} (X : Fin n → Ω → ℝ) :
    MeasurableSpace.generateFrom
      {s | ∃ H : Set (Fin n → ℝ), s = {ω | (fun i => X i ω) ∈ H}} =
    MeasurableSpace.comap (fun ω i => X i ω) ⊤ := by
  rw [MeasurableSpace.comap_eq_generateFrom]
  congr 1
  ext t
  constructor
  · rintro ⟨H, hH⟩
    exact ⟨H, MeasurableSpace.measurableSet_top, hH.symm⟩
  · rintro ⟨s, _, hs⟩
    exact ⟨s, hs.symm⟩

/-- Theorem 5.1(ii): Y is measurable σ(X₁,...,Xₙ) iff Y = f(X₁,...,Xₙ) for some f. -/
theorem measurable_wrt_generated_iff {n : ℕ} (X : Fin n → Ω → ℝ) (Y : Ω → ℝ) :
    @Measurable Ω ℝ (MeasurableSpace.comap (fun ω i => X i ω) ⊤) _ Y ↔
    ∃ f : (Fin n → ℝ) → ℝ, ∀ ω, Y ω = f (fun i => X i ω) := by
  classical
  constructor
  · intro hY
    have hInv : ∀ ω₁ ω₂, (fun i => X i ω₁) = (fun i => X i ω₂) → Y ω₁ = Y ω₂ := by
      intro ω₁ ω₂ hX_eq
      by_contra h_ne
      have hY1_meas : MeasurableSet ({Y ω₁} : Set ℝ) := measurableSet_singleton _
      have hPre := hY hY1_meas
      obtain ⟨S, _, hS⟩ := hPre
      have hω1 : ω₁ ∈ Y ⁻¹' {Y ω₁} := rfl
      have hω2 : ω₂ ∉ Y ⁻¹' {Y ω₁} := by
        simp only [Set.mem_preimage, Set.mem_singleton_iff]
        exact fun h => h_ne h.symm
      rw [← hS] at hω1 hω2
      simp only [Set.mem_preimage] at hω1 hω2
      rw [hX_eq] at hω1
      exact hω2 hω1
    refine ⟨fun v => if h : ∃ ω, (fun i => X i ω) = v then Y h.choose else 0, fun ω => ?_⟩
    have hExists : ∃ ω', (fun i => X i ω') = (fun i => X i ω) := ⟨ω, rfl⟩
    show Y ω =
      (if h : ∃ ω', (fun i => X i ω') = (fun i => X i ω) then Y h.choose else 0)
    rw [dif_pos hExists]
    exact (hInv hExists.choose ω hExists.choose_spec).symm
  · rintro ⟨f, hf⟩
    intro s hs
    refine ⟨f ⁻¹' s, MeasurableSpace.measurableSet_top, ?_⟩
    ext ω
    simp only [Set.mem_preimage, hf ω]

/-! ## Theorem 5.3: Existence of Independent Sequences -/

/-- Theorem 5.3: Existence of independent sequences with prescribed distributions.
Given a sequence of discrete probability measures, there exists a probability space
with independent random variables having these distributions.
The construction uses the unit interval with Lebesgue measure. -/
theorem existence_independent_sequence
    (_distributions : ℕ → ProbabilityMeasure ℝ) :
    ∃ (Ω' : Type) (_ : MeasurableSpace Ω') (P : Measure Ω') (_ : IsProbabilityMeasure P)
      (X : ℕ → Ω' → ℝ),
      (∀ n, Measurable (X n)) ∧
      (∀ n m, n ≠ m → IndepFun (X n) (X m) P) ∧
      ∀ n, P.map (X n) = (_distributions n).toMeasure := by
  -- Kolmogorov's construction: take the infinite product probability space.
  let Ω' : Type := ℕ → ℝ
  let μs : ℕ → Measure ℝ := fun n => (_distributions n).toMeasure
  haveI hprob : ∀ n, IsProbabilityMeasure (μs n) := fun n => inferInstance
  have hjoint : iIndepFun (fun (i : ℕ) (ω : ℕ → ℝ) => ω i)
      (MeasureTheory.Measure.infinitePi μs) := by
    simpa using iIndepFun_infinitePi (Ω := fun _ : ℕ => ℝ) (𝓧 := fun _ : ℕ => ℝ)
      (P := μs) (X := fun _ : ℕ => id) (fun _ => measurable_id)
  refine ⟨Ω', inferInstance, MeasureTheory.Measure.infinitePi μs, inferInstance,
    (fun n ω => ω n), (fun n => measurable_pi_apply n),
    (fun n m hnm => hjoint.indepFun hnm), ?_⟩
  intro n
  exact MeasureTheory.Measure.infinitePi_map_eval μs n

end Mettapedia.AutoBooks.Billingsley.Ch01Sec05

end
