/-
Copyright (c) 2026 Mettapedia Authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Mettapedia Project
-/
import Mathlib.MeasureTheory.OuterMeasure.Basic
import Mathlib.MeasureTheory.OuterMeasure.Caratheodory
import Mathlib.MeasureTheory.OuterMeasure.OfFunction
import Mathlib.MeasureTheory.OuterMeasure.OfAddContent
import Mathlib.MeasureTheory.Measure.MeasureSpace
import Mathlib.MeasureTheory.Measure.AddContent
import Mathlib.MeasureTheory.Measure.MeasuredSets
import Mathlib.MeasureTheory.SetSemiring
import Mathlib.MeasureTheory.SetAlgebra
import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
import Mathlib.MeasureTheory.PiSystem

/-!
# Billingsley Chapter 2, Section 11: Outer Measure

This file formalizes Section 11 of Billingsley's "Probability and Measure" (3rd Edition),
which introduces outer measures, Carathéodory-measurable sets, and the general extension
theorem for measures on a semiring.

## Scope

* The axioms of an outer measure (Billingsley (i)–(iv) above (11.1)): captured by the
  mathlib type `MeasureTheory.OuterMeasure`.
* Example 11.1: the outer measure generated by a set function on any class.
* Carathéodory-measurable sets (Definition (11.2)/(11.3)).
* Theorem 11.1: the Carathéodory σ-field of an outer measure carries an induced measure.
* Theorem 11.2/11.3: extension of a pre-measure on a field (resp. semiring) to a measure
  on the generated σ-field — interface; full construction goes via mathlib's
  `AddContent` / `OuterMeasure.ofFunction` infrastructure.
* The approximation theorem (Theorem 11.4) and Corollary 1 — interface.

## References

* [Billingsley, *Probability and Measure* (3rd ed.), Section 11][billingsley1995]
-/

noncomputable section

open MeasureTheory Set Filter Topology MeasurableSpace
open scoped ENNReal NNReal

namespace Mettapedia.AutoBooks.Billingsley.Ch02Sec11

variable {Ω : Type*}

/-! ## Outer measures: axioms (Billingsley, above (11.1)) -/

/-- An outer measure sends `∅` to `0`. -/
theorem outerMeasure_empty (μ : OuterMeasure Ω) : μ ∅ = 0 := μ.empty

/-- An outer measure is monotone. -/
theorem outerMeasure_mono (μ : OuterMeasure Ω) {A B : Set Ω} (h : A ⊆ B) : μ A ≤ μ B :=
  μ.mono h

/-- An outer measure is countably subadditive. -/
theorem outerMeasure_iUnion_le {μ : OuterMeasure Ω} {ι : Type*} [Countable ι]
    (A : ι → Set Ω) : μ (⋃ i, A i) ≤ ∑' i, μ (A i) :=
  measure_iUnion_le A

/-! ## Example 11.1: outer measure from a set function -/

/-- The outer measure generated by a set function `m : Set Ω → ℝ≥0∞` with `m ∅ = 0`.
Formula: `μ*(A) = inf { ∑' n, m (A n) : A ⊆ ⋃ n, A n }`. This is exactly
`MeasureTheory.OuterMeasure.ofFunction`. -/
def ofSetFunction (m : Set Ω → ℝ≥0∞) (h0 : m ∅ = 0) : OuterMeasure Ω :=
  OuterMeasure.ofFunction m h0

/-! ## Carathéodory-measurable sets (Definition (11.2)) -/

/-- A set `A` is `μ*`-measurable iff for every `E`,
`μ*(A ∩ E) + μ*(Aᶜ ∩ E) = μ*(E)`. Equivalent form via subadditivity:
`μ*(A ∩ E) + μ*(Aᶜ ∩ E) ≤ μ*(E)`. Captured by mathlib as `OuterMeasure.IsCaratheodory`. -/
def IsMuStarMeasurable (μ : OuterMeasure Ω) (A : Set Ω) : Prop :=
  μ.IsCaratheodory A

/-! ## Theorem 11.1: Carathéodory σ-field of an outer measure -/

/-- The Carathéodory σ-field of an outer measure is a measurable space on `Ω`. -/
def caratheodorySigmaAlgebra (μ : OuterMeasure Ω) : MeasurableSpace Ω := μ.caratheodory

/-! ## Theorem 11.2/11.3: extension from a (semi)ring

Mathlib provides the extension as follows. Given an `AddContent m` on a set class `C`
together with σ-subadditivity, the outer measure `OuterMeasure.ofFunction` on the class
extends uniquely to a measure on the Carathéodory σ-field (which contains `generateFrom C`
when `C` is a set semiring).

We expose a clean statement of the existence result; its proof draws on
`MeasureTheory.AddContent`, `MeasureTheory.OuterMeasure.ofFunction` and
Carathéodory's theorem, already in mathlib.
-/

/-- **Theorem 11.3** (Billingsley): A finitely additive, countably subadditive set
function on a semiring extends to a measure on the generated σ-field. -/
theorem extension_from_semiring_exists
    {C : Set (Set Ω)} (hC : IsSetSemiring C) (m : AddContent ℝ≥0∞ C)
    (h_subadd : ∀ (A : Set Ω) (s : ℕ → Set Ω),
      A ∈ C → (∀ n, s n ∈ C) → A ⊆ ⋃ n, s n → m A ≤ ∑' n, m (s n)) :
    ∃ (_mS : MeasurableSpace Ω) (ν : Measure Ω),
      _mS = MeasurableSpace.generateFrom C ∧ (∀ A ∈ C, ν A = m A) := by
  letI mΩ : MeasurableSpace Ω := MeasurableSpace.generateFrom C
  have m_subadd : m.IsSigmaSubadditive := fun f hf hUnion =>
    h_subadd _ f hUnion hf (subset_refl _)
  exact ⟨mΩ, m.measure hC le_rfl m_subadd, rfl,
    fun A hA => m.measure_eq hC rfl m_subadd hA⟩

/-! ## Theorem 11.4: Approximation Theorem -/

/-- **Theorem 11.4(ii)** (Billingsley): If `B` is measurable with finite measure, then it
is arbitrarily close in measure-symmetric-difference to a finite disjoint union of sets
from a generating semiring. -/
theorem approx_by_semiring_union
    {C : Set (Set Ω)} (_hC : IsSetSemiring C) (m : OuterMeasure Ω)
    (_hgen : m.caratheodory = MeasurableSpace.generateFrom C)
    (B : Set Ω) (_hB : m.IsCaratheodory B) (_hfin : m B ≠ ∞)
    (ε : ℝ≥0∞) (_hε : ε ≠ 0) :
    ∃ (n : ℕ) (A : Fin n → Set Ω),
      (∀ i, A i ∈ C) ∧ Pairwise (Function.onFun Disjoint A) ∧
      m (symmDiff B (⋃ i, A i)) ≤ ε := by
  sorry

/-- **Corollary 1** (Billingsley): For a finite measure on a σ-field generated by a
*field*, every measurable set is symmetric-difference close to a set in the field. -/
theorem approx_by_field {Ω : Type*} [mΩ : MeasurableSpace Ω] {C : Set (Set Ω)}
    (hC_alg : IsSetAlgebra C) (μ : Measure Ω) [IsFiniteMeasure μ]
    (hgen : mΩ = MeasurableSpace.generateFrom C) (A : Set Ω) (hA : MeasurableSet A)
    (ε : ℝ≥0∞) (hε : ε ≠ 0) :
    ∃ B ∈ C, μ (symmDiff A B) ≤ ε := by
  have hring : IsSetRing C := hC_alg.isSetRing
  -- Since the algebra contains `univ`, the covering condition is trivial.
  have h'C : ∃ D : Set (Set Ω), D.Countable ∧ D ⊆ C ∧ μ (⋃₀ D)ᶜ = 0 := by
    refine ⟨{Set.univ}, Set.countable_singleton _, ?_, ?_⟩
    · simpa using hC_alg.univ_mem
    · simp
  have hε' : 0 < ε := pos_iff_ne_zero.mpr hε
  obtain ⟨t, htC, ht⟩ :=
    exists_measure_symmDiff_lt_of_generateFrom_isSetRing (μ := μ) hring h'C hgen hA hε'
  refine ⟨t, htC, ?_⟩
  rw [symmDiff_comm]
  exact ht.le

end Mettapedia.AutoBooks.Billingsley.Ch02Sec11
