/-
Copyright (c) 2026 Mettapedia Authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Mettapedia Project
-/
import Mathlib.MeasureTheory.Measure.MeasureSpace
import Mathlib.MeasureTheory.Measure.MeasureSpaceDef
import Mathlib.MeasureTheory.Measure.Restrict
import Mathlib.MeasureTheory.Measure.Count
import Mathlib.MeasureTheory.Measure.Typeclasses.SFinite
import Mathlib.MeasureTheory.PiSystem
import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
import Mathlib.MeasureTheory.MeasurableSpace.Pi
import Mathlib.MeasureTheory.OuterMeasure.BorelCantelli
import Mathlib.Data.Real.Basic

/-!
# Billingsley Chapter 2, Section 10: General Measures

This file formalizes Section 10 of Billingsley's "Probability and Measure" (3rd Edition),
generalizing the probability-measure machinery of Chapter 1 to arbitrary measures with
values in `[0, ∞]`.

## Scope

* Classes of sets: Borel σ-fields on `ℝ` and `ℝ^k` (Example 10.1); the trace σ-field
  (Theorem 10.1).
* The extended-real arithmetic used throughout (Billingsley equations (10.3)–(10.4));
  this is mathlib's `ENNReal`.
* General measures on a σ-field: σ-finiteness, support, measure-space terminology.
* Monotonicity, finite/countable subadditivity, inclusion–exclusion (Billingsley (10.5)),
  continuity from below and above (Theorem 10.2).
* Uniqueness on a π-system for σ-finite measures (Theorem 10.3) and for finite measures
  with a countable covering by π-system sets (Theorem 10.4).

Throughout we lean on `MeasureTheory.Measure` and friends. Billingsley's "field" is a
`MeasureTheory.IsSetAlgebra`; his "σ-field" is `MeasurableSpace`; his "π-system" is
`IsPiSystem`. The extension from a pre-measure on a field to a measure on the generated
σ-field is the subject of Section 11.

## References

* [Billingsley, *Probability and Measure* (3rd ed.), Section 10][billingsley1995]
-/

noncomputable section

open MeasureTheory Set Filter Topology MeasurableSpace
open scoped ENNReal NNReal

namespace Mettapedia.AutoBooks.Billingsley.Ch02Sec10

/-! ## Classes of Sets (Example 10.1, Theorem 10.1) -/

/-- The Borel σ-field on `ℝ` is generated by the open sets. -/
example : MeasurableSpace ℝ := borel ℝ

/-- The Borel σ-field on `ℝ^k`: the product Borel structure. -/
example (k : ℕ) : MeasurableSpace (Fin k → ℝ) := inferInstance

/-- Trace σ-field: if `S` is a σ-field in `Ω`, then `S` restricted to a subset `Ω₀`
is the σ-field of all intersections `A ∩ Ω₀` for `A ∈ S`. In mathlib this is the
instance `Subtype.instMeasurableSpace`. -/
def traceSigmaAlgebra {Ω : Type*} [MeasurableSpace Ω] (Ω₀ : Set Ω) :
    MeasurableSpace Ω₀ := Subtype.instMeasurableSpace

/-! ## Measure-space terminology -/

/-- A measure space is a triple `(Ω, 𝓕, μ)` with `μ` a measure on the σ-field `𝓕`.
In mathlib this is packaged as `MeasureSpace` (measure in type class), or explicitly
via `(μ : Measure Ω)` with `MeasurableSpace Ω` in scope. -/
example (Ω : Type*) [MeasurableSpace Ω] (μ : Measure Ω) : Measure Ω := μ

/-- A support of a measure is a measurable set whose complement has measure zero. -/
def IsSupport {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω) (A : Set Ω) : Prop :=
  MeasurableSet A ∧ μ Aᶜ = 0

/-- A finite measure is concentrated on any support. -/
theorem measure_eq_of_isSupport_of_isFiniteMeasure {Ω : Type*} [MeasurableSpace Ω]
    (μ : Measure Ω) [IsFiniteMeasure μ] {A : Set Ω} (h : IsSupport μ A) :
    μ A = μ Set.univ := by
  obtain ⟨hA, hAc⟩ := h
  have hsplit : μ Set.univ = μ A + μ Aᶜ := by
    have h_union : (Set.univ : Set Ω) = A ∪ Aᶜ := by
      rw [Set.union_compl_self]
    rw [h_union]
    exact measure_union disjoint_compl_right hA.compl
  rw [hsplit, hAc, add_zero]

/-! ## Core properties of a general measure (Theorem 10.2) -/

variable {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω)

/-- Monotonicity: `A ⊆ B ⇒ μ A ≤ μ B`. -/
theorem measure_mono' {A B : Set Ω} (h : A ⊆ B) : μ A ≤ μ B := measure_mono h

/-- Finite additivity for two disjoint sets when the second is measurable. -/
theorem measure_union_disjoint {A B : Set Ω}
    (hAB : Disjoint A B) (hB : MeasurableSet B) :
    μ (A ∪ B) = μ A + μ B := measure_union hAB hB

/-- Finite subadditivity: `μ (A ∪ B) ≤ μ A + μ B`. -/
theorem measure_union_le' (A B : Set Ω) : μ (A ∪ B) ≤ μ A + μ B :=
  measure_union_le A B

/-- Countable subadditivity. -/
theorem measure_iUnion_le_countable {ι : Type*} [Countable ι] (A : ι → Set Ω) :
    μ (⋃ i, A i) ≤ ∑' i, μ (A i) := measure_iUnion_le A

/-- Inclusion–exclusion for two sets (Billingsley (10.5) with n = 2). The identity
`μ(A ∪ B) + μ(A ∩ B) = μ A + μ B` holds without finiteness hypotheses. -/
theorem measure_union_add_inter' {A B : Set Ω} (hB : MeasurableSet B) :
    μ (A ∪ B) + μ (A ∩ B) = μ A + μ B :=
  measure_union_add_inter A hB

/-- Continuity from below: `A n ↑ ⋃ n, A n` implies `μ (A n) → μ (⋃ n, A n)`. -/
theorem tendsto_measure_iUnion_monotone
    {A : ℕ → Set Ω} (hA : Monotone A) :
    Filter.Tendsto (fun n => μ (A n)) Filter.atTop (𝓝 (μ (⋃ n, A n))) :=
  tendsto_measure_iUnion_atTop hA

/-- Continuity from above: `A n ↓ ⋂ n, A n` with `μ (A 0) < ∞` implies
`μ (A n) → μ (⋂ n, A n)`. -/
theorem tendsto_measure_iInter_antitone
    {A : ℕ → Set Ω} (hA : ∀ n, MeasurableSet (A n)) (hAnti : Antitone A)
    (hfin : μ (A 0) ≠ ∞) :
    Filter.Tendsto (fun n => μ (A n)) Filter.atTop (𝓝 (μ (⋂ n, A n))) :=
  tendsto_measure_iInter_atTop (fun n => (hA n).nullMeasurableSet) hAnti ⟨0, hfin⟩

/-! ## No uncountable disjoint family of positive measure (Theorem 10.2 (iv)) -/

/-- If `μ` is σ-finite then any pairwise-disjoint family of measurable sets has at most
countably many members of positive measure. This is Theorem 10.2 (iv). We state it via
mathlib's `countable_meas_pos_of_disjoint_iUnion`. -/
theorem countable_pos_measure_of_disjoint_of_sigmaFinite
    [SigmaFinite μ] {ι : Type*} {s : ι → Set Ω}
    (hmeas : ∀ i, MeasurableSet (s i))
    (hdisj : Pairwise (Function.onFun Disjoint s)) :
    Set.Countable {i : ι | 0 < μ (s i)} :=
  Measure.countable_meas_pos_of_disjoint_iUnion (μ := μ) hmeas hdisj

/-! ## Uniqueness of measures (Theorem 10.3, 10.4) -/

/-- Two σ-finite measures that agree on a π-system generating the σ-field agree. This
packages `MeasureTheory.Measure.ext_of_generateFrom_of_iUnion` for the Billingsley-style
hypothesis set. -/
theorem ext_of_generateFrom_of_pi_of_cover
    {S : Set (Set Ω)} (hS_gen : ‹MeasurableSpace Ω› = MeasurableSpace.generateFrom S)
    (hS_pi : IsPiSystem S) {μ ν : Measure Ω}
    (hcov : ∃ (u : ℕ → Set Ω),
      (∀ n, u n ∈ S) ∧ (⋃ n, u n) = Set.univ ∧ (∀ n, μ (u n) ≠ ∞))
    (hμν : ∀ A ∈ S, μ A = ν A) : μ = ν := by
  obtain ⟨u, huS, hucov, hufin⟩ := hcov
  exact Measure.ext_of_generateFrom_of_iUnion S u hS_gen hS_pi hucov huS hufin hμν

/-- Simplified uniqueness for finite measures when `Ω` is a countable union of π-system
sets (Theorem 10.4). -/
theorem ext_of_generateFrom_of_pi_of_cover_finite
    {S : Set (Set Ω)} (hS_gen : ‹MeasurableSpace Ω› = MeasurableSpace.generateFrom S)
    (hS_pi : IsPiSystem S) {μ ν : Measure Ω}
    [IsFiniteMeasure μ]
    (hcov : ∃ (u : ℕ → Set Ω), (∀ n, u n ∈ S) ∧ (⋃ n, u n) = Set.univ)
    (hμν : ∀ A ∈ S, μ A = ν A) : μ = ν := by
  obtain ⟨u, huS, hucov⟩ := hcov
  exact ext_of_generateFrom_of_pi_of_cover (S := S)
    (hS_gen := hS_gen) (hS_pi := hS_pi) (μ := μ) (ν := ν)
    (hcov := ⟨u, huS, hucov, fun n => (measure_lt_top μ (u n)).ne⟩) (hμν := hμν)

/-! ## Restriction of a measure (Example 10.4) -/

/-- Restriction of a measure to a measurable set, packaged as a measure on `Ω`. -/
def restrictToSet (μ : Measure Ω) (A : Set Ω) : Measure Ω := μ.restrict A

@[simp]
theorem restrictToSet_apply (μ : Measure Ω) {A B : Set Ω} (hB : MeasurableSet B) :
    restrictToSet μ A B = μ (B ∩ A) :=
  Measure.restrict_apply hB

/-! ## Counting measure (Example 10.3) -/

/-- Counting measure on any measurable space. -/
def countingMeasure : Measure Ω := Measure.count

theorem countingMeasure_apply_finite [MeasurableSingletonClass Ω] {A : Set Ω}
    (hA : A.Finite) : countingMeasure (Ω := Ω) A = A.toFinset.card := by
  classical
  simp [countingMeasure, Measure.count_apply_finite _ hA]

/-! ## Problem 10.1: conditions (i) and (iii) plus some finite value imply (ii). -/

/-- For any mathlib `Measure`, `μ ∅ = 0` is tautological (baked into the structure). This
records Billingsley's Problem 10.1 by observation. -/
theorem measure_empty' : μ (∅ : Set Ω) = 0 := measure_empty

/-! ## Problem 10.4 (partial): Borel–Cantelli-style `limsup` zero. -/

/-- If `∑ μ(Aₙ) < ∞` then `μ(limsup Aₙ) = 0` (Borel–Cantelli, from mathlib). Billingsley's
Problem 10.4 (b) singles out the finiteness hypothesis as necessary. -/
theorem measure_limsup_atTop_eq_zero_of_tsum_ne_top {A : ℕ → Set Ω}
    (h : (∑' n, μ (A n)) ≠ ∞) :
    μ (Filter.limsup A Filter.atTop) = 0 :=
  MeasureTheory.measure_limsup_atTop_eq_zero h

end Mettapedia.AutoBooks.Billingsley.Ch02Sec10
