import Mettapedia.FluidDynamics.NavierStokes.NavierStokesBKMContinuationTarget
import Mettapedia.FluidDynamics.NavierStokes.NavierStokesFiniteModeBoundedEnergy

/-!
# Uniform Vorticity Control for the Two-Mode Schwartz Ansatz

This file closes the concrete BKM-side analytic input for the bounded two-mode
Schwartz ansatz. The key point is that the spatial derivatives of a Schwartz
profile are uniformly bounded by the first Schwartz seminorm, so the vorticity
of any bounded scalar two-mode combination is uniformly controlled on every
time slab.
-/

set_option autoImplicit false

noncomputable section

namespace Mettapedia
namespace FluidDynamics
namespace NavierStokes

/-- A crude but explicit global bound for the vorticity of the time-independent
velocity seed generated by a Schwartz initial profile. -/
def schwartzInitialVelocityVorticityBound
    (f : NSSchwartzInitialVelocity) : ℝ :=
  6 * (SchwartzMap.seminorm ℝ 0 1 f)

theorem schwartzInitialVelocityVorticityBound_nonneg
    (f : NSSchwartzInitialVelocity) :
    0 ≤ schwartzInitialVelocityVorticityBound f := by
  unfold schwartzInitialVelocityVorticityBound
  positivity

/-- A uniform pointwise bound on all coordinate derivatives entering the
concrete curl gives a slabwise uniform vorticity bound. -/
theorem uniformVorticityBoundUpTo_of_abs_spatialDerivativeComponent_le
    {u : NSVelocityField} {T K : ℝ}
    (hK : 0 ≤ K)
    (hderiv : ∀ t x, 0 ≤ t → t ≤ T →
      ∀ coord comp : Fin 3, |spatialDerivativeComponent u t x coord comp| ≤ K) :
    uniformVorticityBoundUpTo u T (6 * K) := by
  constructor
  · nlinarith
  · intro t x ht0 htT
    exact
      norm_spatialVorticity_le_of_abs_spatialDerivativeComponent_le
        (u := u) (t := t) (x := x) (K := K)
        (hderiv t x ht0 htT)

/-- The Fréchet derivative of a Schwartz profile is uniformly bounded by the
first Schwartz seminorm. -/
theorem norm_fderiv_schwartzInitialVelocity_le_seminorm
    (f : NSSchwartzInitialVelocity) (x : NSSpace) :
    ‖fderiv ℝ (f : NSInitialVelocity) x‖ ≤
      SchwartzMap.seminorm ℝ 0 1 f := by
  simpa using (SchwartzMap.norm_iteratedFDeriv_le_seminorm ℝ f 1 x)

/-- Every coordinate directional derivative of a time-independent Schwartz seed
is uniformly bounded by the first Schwartz seminorm. -/
theorem norm_spatialDerivativeDirection_timeIndependentVelocity_le_seminorm
    (f : NSSchwartzInitialVelocity) (coord : Fin 3) (t : NSTime) (x : NSSpace) :
    ‖spatialFDeriv (timeIndependentVelocity (f : NSInitialVelocity)) t x
        (EuclideanSpace.single coord (1 : ℝ))‖ ≤
      SchwartzMap.seminorm ℝ 0 1 f := by
  calc
    ‖spatialFDeriv (timeIndependentVelocity (f : NSInitialVelocity)) t x
        (EuclideanSpace.single coord (1 : ℝ))‖
      = ‖fderiv ℝ (f : NSInitialVelocity) x
          (EuclideanSpace.single coord (1 : ℝ))‖ := by
          rfl
    _ ≤ ‖fderiv ℝ (f : NSInitialVelocity) x‖ *
          ‖EuclideanSpace.single coord (1 : ℝ)‖ := by
          simpa using
            (ContinuousLinearMap.le_opNorm
              (fderiv ℝ (f : NSInitialVelocity) x)
              (EuclideanSpace.single coord (1 : ℝ)))
    _ = ‖fderiv ℝ (f : NSInitialVelocity) x‖ := by simp
    _ ≤ SchwartzMap.seminorm ℝ 0 1 f :=
      norm_fderiv_schwartzInitialVelocity_le_seminorm f x

/-- Every scalar coordinate derivative entering the vorticity of a
time-independent Schwartz seed is uniformly bounded by the first Schwartz
seminorm. -/
theorem abs_spatialDerivativeComponent_timeIndependentVelocity_le_seminorm
    (f : NSSchwartzInitialVelocity) (coord comp : Fin 3) (t : NSTime) (x : NSSpace) :
    |spatialDerivativeComponent
        (timeIndependentVelocity (f : NSInitialVelocity)) t x coord comp| ≤
      SchwartzMap.seminorm ℝ 0 1 f := by
  unfold spatialDerivativeComponent
  calc
    |(spatialFDeriv (timeIndependentVelocity (f : NSInitialVelocity)) t x
        (EuclideanSpace.single coord (1 : ℝ))) comp|
      =
        ‖(spatialFDeriv (timeIndependentVelocity (f : NSInitialVelocity)) t x
          (EuclideanSpace.single coord (1 : ℝ))) comp‖ := by
          simp
    _ ≤ ‖spatialFDeriv (timeIndependentVelocity (f : NSInitialVelocity)) t x
          (EuclideanSpace.single coord (1 : ℝ))‖ := by
          simpa using
            (PiLp.norm_apply_le
              (spatialFDeriv (timeIndependentVelocity (f : NSInitialVelocity)) t x
                (EuclideanSpace.single coord (1 : ℝ))) comp)
    _ ≤ SchwartzMap.seminorm ℝ 0 1 f :=
      norm_spatialDerivativeDirection_timeIndependentVelocity_le_seminorm
        f coord t x

/-- The vorticity of the time-independent Schwartz seed is uniformly bounded by
an explicit multiple of the first Schwartz seminorm. -/
theorem norm_spatialVorticity_timeIndependentVelocity_le_schwartzInitialVelocityVorticityBound
    (f : NSSchwartzInitialVelocity) (t : NSTime) (x : NSSpace) :
    ‖spatialVorticity (timeIndependentVelocity (f : NSInitialVelocity)) t x‖ ≤
      schwartzInitialVelocityVorticityBound f := by
  simpa [schwartzInitialVelocityVorticityBound] using
    (norm_spatialVorticity_le_of_abs_spatialDerivativeComponent_le
      (u := timeIndependentVelocity (f : NSInitialVelocity)) (t := t) (x := x)
      (K := SchwartzMap.seminorm ℝ 0 1 f)
      (by
        intro coord comp
        exact
          abs_spatialDerivativeComponent_timeIndependentVelocity_le_seminorm
            f coord comp t x))

/-- A time-independent Schwartz velocity seed has a uniform slabwise vorticity
bound on every time horizon, controlled by its first Schwartz seminorm. -/
theorem uniformVorticityBoundUpTo_timeIndependentVelocity
    (f : NSSchwartzInitialVelocity) (T : ℝ) :
    uniformVorticityBoundUpTo
      (timeIndependentVelocity (f : NSInitialVelocity)) T
      (schwartzInitialVelocityVorticityBound f) := by
  constructor
  · exact schwartzInitialVelocityVorticityBound_nonneg f
  · intro t x _ht0 _htT
    exact
      norm_spatialVorticity_timeIndependentVelocity_le_schwartzInitialVelocityVorticityBound
        f t x

/-- The same time-independent Schwartz seed supplies its own BKM envelope on
every time horizon. -/
theorem timeIndependentVelocity_exhibits_BKMEnvelope
    (f : NSSchwartzInitialVelocity) (T : ℝ) :
    ∃ Ω : NSTime → ℝ, ∃ Bint : ℝ,
      vorticityEnvelopeOn (timeIndependentVelocity (f : NSInitialVelocity)) T Ω ∧
        integrableVorticityEnvelopeOn Ω T Bint := by
  exact
    uniformVorticityBoundUpTo_implies_BKMEnvelope
      (u := timeIndependentVelocity (f : NSInitialVelocity))
      (T := T)
      (B := schwartzInitialVelocityVorticityBound f)
      (uniformVorticityBoundUpTo_timeIndependentVelocity f T)

/-- On a nonnegative slab, a time-independent Schwartz velocity seed has the
constant BKM envelope induced by its first-seminorm vorticity bound. -/
theorem timeIndependentVelocity_has_constantBKMEnvelope
    (f : NSSchwartzInitialVelocity) {T : ℝ} (hT : 0 ≤ T) :
    vorticityEnvelopeOn
        (timeIndependentVelocity (f : NSInitialVelocity)) T
        (fun _ : NSTime => schwartzInitialVelocityVorticityBound f) ∧
      integrableVorticityEnvelopeOn
        (fun _ : NSTime => schwartzInitialVelocityVorticityBound f)
        T
        (T * schwartzInitialVelocityVorticityBound f) := by
  exact
    uniformVorticityBoundUpTo_implies_constantBKMEnvelope
      (u := timeIndependentVelocity (f : NSInitialVelocity))
      (T := T)
      (B := schwartzInitialVelocityVorticityBound f)
      hT
      (uniformVorticityBoundUpTo_timeIndependentVelocity f T)

/-- Any external nonnegative BKM budget that dominates the explicit Schwartz
vorticity bound gives a constant BKM envelope for the time-independent seed. -/
theorem timeIndependentVelocity_has_constantBKMEnvelope_of_bound_ge
    (f : NSSchwartzInitialVelocity) {T B : ℝ}
    (hT : 0 ≤ T)
    (hB : schwartzInitialVelocityVorticityBound f ≤ B) :
    vorticityEnvelopeOn
        (timeIndependentVelocity (f : NSInitialVelocity)) T
        (fun _ : NSTime => B) ∧
      integrableVorticityEnvelopeOn
        (fun _ : NSTime => B)
        T
        (T * B) := by
  exact
    uniformVorticityBoundUpTo_implies_constantBKMEnvelope
      (u := timeIndependentVelocity (f : NSInitialVelocity))
      (T := T)
      (B := B)
      hT
      (uniformVorticityBoundUpTo_mono
        (uniformVorticityBoundUpTo_timeIndependentVelocity f T)
        hB)

/-- At each time slice, the two-mode Schwartz ansatz has vorticity equal to the
same scalar combination of the profile vorticities. -/
theorem spatialVorticity_twoModeSchwartzVelocity
    (a b : NSTime → ℝ) (f g : NSSchwartzInitialVelocity) (t : NSTime) (x : NSSpace) :
    spatialVorticity (twoModeSchwartzVelocity a b f g) t x =
      a t • spatialVorticity (timeIndependentVelocity (f : NSInitialVelocity)) t x +
        b t • spatialVorticity (timeIndependentVelocity (g : NSInitialVelocity)) t x := by
  have hf :
      DifferentiableAt ℝ
        (fun y : NSSpace => timeIndependentVelocity (f : NSInitialVelocity) t y) x := by
    simpa [timeIndependentVelocity] using f.differentiableAt
  have hg :
      DifferentiableAt ℝ
        (fun y : NSSpace => timeIndependentVelocity (g : NSInitialVelocity) t y) x := by
    simpa [timeIndependentVelocity] using g.differentiableAt
  change
    spatialVorticity
      ((a t) • timeIndependentVelocity (f : NSInitialVelocity) +
        (b t) • timeIndependentVelocity (g : NSInitialVelocity)) t x = _
  simpa using
    (spatialVorticity_linearCombination
      (u := timeIndependentVelocity (f : NSInitialVelocity))
      (v := timeIndependentVelocity (g : NSInitialVelocity))
      (a := a t) (b := b t) hf hg)

/-- Uniformly bounded scalar amplitudes give an explicit uniform slab
vorticity bound for the two-mode Schwartz ansatz. -/
theorem uniformVorticityBoundUpTo_twoModeSchwartzVelocity_of_abs_le
    (a b : NSTime → ℝ) (f g : NSSchwartzInitialVelocity) (A B T : ℝ)
    (haBound : ∀ t, |a t| ≤ A)
    (hbBound : ∀ t, |b t| ≤ B) :
    uniformVorticityBoundUpTo (twoModeSchwartzVelocity a b f g) T
      (A * schwartzInitialVelocityVorticityBound f +
        B * schwartzInitialVelocityVorticityBound g) := by
  have hA : 0 ≤ A := le_trans (abs_nonneg (a 0)) (haBound 0)
  have hB : 0 ≤ B := le_trans (abs_nonneg (b 0)) (hbBound 0)
  constructor
  · exact add_nonneg
      (mul_nonneg hA (schwartzInitialVelocityVorticityBound_nonneg f))
      (mul_nonneg hB (schwartzInitialVelocityVorticityBound_nonneg g))
  · intro t x ht0 htT
    rw [spatialVorticity_twoModeSchwartzVelocity a b f g t x]
    calc
      ‖a t • spatialVorticity (timeIndependentVelocity (f : NSInitialVelocity)) t x +
          b t • spatialVorticity (timeIndependentVelocity (g : NSInitialVelocity)) t x‖
        ≤
          ‖a t • spatialVorticity (timeIndependentVelocity (f : NSInitialVelocity)) t x‖ +
            ‖b t • spatialVorticity (timeIndependentVelocity (g : NSInitialVelocity)) t x‖ := by
            exact norm_add_le _ _
      _ =
          |a t| *
              ‖spatialVorticity (timeIndependentVelocity (f : NSInitialVelocity)) t x‖ +
            |b t| *
              ‖spatialVorticity (timeIndependentVelocity (g : NSInitialVelocity)) t x‖ := by
            simp [norm_smul, Real.norm_eq_abs]
      _ ≤
          |a t| * schwartzInitialVelocityVorticityBound f +
            |b t| * schwartzInitialVelocityVorticityBound g := by
            gcongr
            · exact
                norm_spatialVorticity_timeIndependentVelocity_le_schwartzInitialVelocityVorticityBound
                  f t x
            · exact
                norm_spatialVorticity_timeIndependentVelocity_le_schwartzInitialVelocityVorticityBound
                  g t x
      _ ≤
          A * schwartzInitialVelocityVorticityBound f +
            B * schwartzInitialVelocityVorticityBound g := by
            exact add_le_add
              (mul_le_mul_of_nonneg_right
                (haBound t) (schwartzInitialVelocityVorticityBound_nonneg f))
              (mul_le_mul_of_nonneg_right
                (hbBound t) (schwartzInitialVelocityVorticityBound_nonneg g))

/-- The same explicit slab vorticity bound yields a BKM envelope for the
two-mode Schwartz ansatz without any extra vorticity hypothesis. -/
theorem twoModeSchwartzVelocity_exhibits_BKMEnvelope_of_abs_le
    (a b : NSTime → ℝ) (f g : NSSchwartzInitialVelocity) (A B T : ℝ)
    (haBound : ∀ t, |a t| ≤ A)
    (hbBound : ∀ t, |b t| ≤ B) :
    ∃ Ω : NSTime → ℝ, ∃ Bint : ℝ,
      vorticityEnvelopeOn (twoModeSchwartzVelocity a b f g) T Ω ∧
        integrableVorticityEnvelopeOn Ω T Bint := by
  exact
    uniformVorticityBoundUpTo_implies_BKMEnvelope
      (u := twoModeSchwartzVelocity a b f g) (T := T)
      (B := A * schwartzInitialVelocityVorticityBound f +
        B * schwartzInitialVelocityVorticityBound g)
      (uniformVorticityBoundUpTo_twoModeSchwartzVelocity_of_abs_le
        a b f g A B T haBound hbBound)

/-- On a nonnegative slab, the bounded two-mode Schwartz ansatz has the
constant BKM envelope induced by the explicit vorticity bound. -/
theorem twoModeSchwartzVelocity_has_constantBKMEnvelope_of_abs_le
    (a b : NSTime → ℝ) (f g : NSSchwartzInitialVelocity) (A B T : ℝ)
    (hT : 0 ≤ T)
    (haBound : ∀ t, |a t| ≤ A)
    (hbBound : ∀ t, |b t| ≤ B) :
    vorticityEnvelopeOn (twoModeSchwartzVelocity a b f g) T
        (fun _ : NSTime =>
          A * schwartzInitialVelocityVorticityBound f +
            B * schwartzInitialVelocityVorticityBound g) ∧
      integrableVorticityEnvelopeOn
        (fun _ : NSTime =>
          A * schwartzInitialVelocityVorticityBound f +
            B * schwartzInitialVelocityVorticityBound g)
        T
        (T *
          (A * schwartzInitialVelocityVorticityBound f +
            B * schwartzInitialVelocityVorticityBound g)) := by
  exact
    uniformVorticityBoundUpTo_implies_constantBKMEnvelope
      (u := twoModeSchwartzVelocity a b f g) (T := T)
      (B :=
        A * schwartzInitialVelocityVorticityBound f +
          B * schwartzInitialVelocityVorticityBound g)
      hT
      (uniformVorticityBoundUpTo_twoModeSchwartzVelocity_of_abs_le
        a b f g A B T haBound hbBound)

/-- Any external constant BKM budget that dominates the explicit two-mode
Schwartz vorticity bound gives a constant BKM envelope for the same ansatz. -/
theorem twoModeSchwartzVelocity_has_constantBKMEnvelope_of_abs_le_of_bound_ge
    (a b : NSTime → ℝ) (f g : NSSchwartzInitialVelocity) (A B C T : ℝ)
    (hT : 0 ≤ T)
    (haBound : ∀ t, |a t| ≤ A)
    (hbBound : ∀ t, |b t| ≤ B)
    (hC :
      A * schwartzInitialVelocityVorticityBound f +
        B * schwartzInitialVelocityVorticityBound g ≤ C) :
    vorticityEnvelopeOn (twoModeSchwartzVelocity a b f g) T
        (fun _ : NSTime => C) ∧
      integrableVorticityEnvelopeOn
        (fun _ : NSTime => C)
        T
        (T * C) := by
  exact
    uniformVorticityBoundUpTo_implies_constantBKMEnvelope
      (u := twoModeSchwartzVelocity a b f g)
      (T := T)
      (B := C)
      hT
      (uniformVorticityBoundUpTo_mono
        (uniformVorticityBoundUpTo_twoModeSchwartzVelocity_of_abs_le
          a b f g A B T haBound hbBound)
        hC)

/-- The constant-one two-mode Schwartz branch has the expected explicit
uniform vorticity bound: the two profile bounds add.  This is the concrete
branch used by the finite-mode obstruction route. -/
theorem uniformVorticityBoundUpTo_oneOneTwoModeSchwartzVelocity
    (f g : NSSchwartzInitialVelocity) (T : ℝ) :
    uniformVorticityBoundUpTo
      (twoModeSchwartzVelocity (fun _ : NSTime => 1) (fun _ : NSTime => 1) f g) T
      (schwartzInitialVelocityVorticityBound f +
        schwartzInitialVelocityVorticityBound g) := by
  simpa using
    (uniformVorticityBoundUpTo_twoModeSchwartzVelocity_of_abs_le
      (fun _ : NSTime => 1) (fun _ : NSTime => 1) f g 1 1 T
      (by intro t; simp) (by intro t; simp))

/-- The constant-one two-mode Schwartz branch supplies its own BKM envelope on
every time horizon. -/
theorem oneOneTwoModeSchwartzVelocity_exhibits_BKMEnvelope
    (f g : NSSchwartzInitialVelocity) (T : ℝ) :
    ∃ Ω : NSTime → ℝ, ∃ Bint : ℝ,
      vorticityEnvelopeOn
          (twoModeSchwartzVelocity (fun _ : NSTime => 1) (fun _ : NSTime => 1) f g)
          T Ω ∧
        integrableVorticityEnvelopeOn Ω T Bint := by
  exact
    uniformVorticityBoundUpTo_implies_BKMEnvelope
      (u := twoModeSchwartzVelocity (fun _ : NSTime => 1) (fun _ : NSTime => 1) f g)
      (T := T)
      (B := schwartzInitialVelocityVorticityBound f +
        schwartzInitialVelocityVorticityBound g)
      (uniformVorticityBoundUpTo_oneOneTwoModeSchwartzVelocity f g T)

/-- On a nonnegative slab, the constant-one two-mode Schwartz branch has the
constant BKM envelope with linear integral bound from the sum of the two profile
vorticity bounds. -/
theorem oneOneTwoModeSchwartzVelocity_has_constantBKMEnvelope
    (f g : NSSchwartzInitialVelocity) {T : ℝ} (hT : 0 ≤ T) :
    vorticityEnvelopeOn
        (twoModeSchwartzVelocity (fun _ : NSTime => 1) (fun _ : NSTime => 1) f g)
        T
        (fun _ : NSTime =>
          schwartzInitialVelocityVorticityBound f +
            schwartzInitialVelocityVorticityBound g) ∧
      integrableVorticityEnvelopeOn
        (fun _ : NSTime =>
          schwartzInitialVelocityVorticityBound f +
            schwartzInitialVelocityVorticityBound g)
        T
        (T *
          (schwartzInitialVelocityVorticityBound f +
            schwartzInitialVelocityVorticityBound g)) := by
  simpa using
    (twoModeSchwartzVelocity_has_constantBKMEnvelope_of_abs_le
      (fun _ : NSTime => 1) (fun _ : NSTime => 1) f g 1 1 T hT
      (by intro t; simp) (by intro t; simp))

end NavierStokes
end FluidDynamics
end Mettapedia
