-- Root module for the FourColor library.
-- Keep the default surface limited to the live Ben-v23 route interfaces and
-- the small shared core. Legacy exploratory geometry/proof files stay in the
-- repository but are intentionally excluded from the root build surface until
-- they are reintegrated honestly.
import FourColor.Basic
import FourColor.GoertzelV23.RouteInterface
import FourColor.GoertzelV23.Section4Target
import FourColor.GoertzelV23.Section4ConcreteTarget
import FourColor.GoertzelV23.Section4PurificationTarget
import FourColor.GoertzelV23.Section4PurifiedFaceTarget
import FourColor.GoertzelV23.Section4MeridionalTarget
import FourColor.GoertzelV23.Section4AnnihilatorTarget
import FourColor.GoertzelV23.Section4AnnihilatorAssembly
import FourColor.GoertzelV23.Section4DecompositionAssembly
import FourColor.GoertzelV23.Section4ChapterAssembly
import FourColor.GoertzelV23.Section6BoundaryTarget
import FourColor.GoertzelV23.Section6RepairBasisTarget
import FourColor.GoertzelV23.Section6ExceptionalPairingTarget
import FourColor.GoertzelV23.Section6Target
import FourColor.GoertzelV23.Section6ChapterAssembly
import FourColor.GoertzelV23.Section7BoundedInteractionTarget
import FourColor.GoertzelV23.Section7GateReductionTarget
import FourColor.GoertzelV23.Section7TubeForcingTarget
import FourColor.GoertzelV23.Section7LocalityTarget
import FourColor.GoertzelV23.Section7Target
import FourColor.GoertzelV23.Section7ChapterAssembly
import FourColor.GoertzelV23.Section8CollarDecompositionTarget
import FourColor.GoertzelV23.Section8BoundarySafeLiftTarget
import FourColor.GoertzelV23.Section8BoundarySafetyTarget
import FourColor.GoertzelV23.Section8CollarMatchTarget
import FourColor.GoertzelV23.Section8CollarClosureTarget
import FourColor.GoertzelV23.Section8NoCutOpenSeamCrossingTarget
import FourColor.GoertzelV23.Section8SeamInterfacePreservationTarget
import FourColor.GoertzelV23.Section8SeamTouchAvoidanceTarget
import FourColor.GoertzelV23.Section8CutOpenSeamPreservationTarget
import FourColor.GoertzelV23.Section8CutOpenTransferTarget
import FourColor.GoertzelV23.Section8CollarReachabilityTarget
import FourColor.GoertzelV23.Section8CanonicalExecutionTarget
import FourColor.GoertzelV23.Section8CutOpenReachabilityAssembly
import FourColor.GoertzelV23.Section8FixedBoundaryPreservationTarget
import FourColor.GoertzelV23.Section8LiftBackTarget
import FourColor.GoertzelV23.Section8RealizedCorrectionTarget
import FourColor.GoertzelV23.Section8CompositionTarget
import FourColor.GoertzelV23.Section8Target
import FourColor.GoertzelV23.Section8ChapterAssembly
import FourColor.GoertzelV23.Section9ClosureTarget
import FourColor.GoertzelV23.Section9ScheduledClosureTarget
import FourColor.GoertzelV23.MiddleAssembly
import FourColor.GoertzelV23.MiddleChapterAssembly
import FourColor.GoertzelV23.MiddleScheduledClosureAssembly
